✨💄  Clm 520 - Users - add user to group modal
italanta/elewa pull request #1032
Opened 2024-09-24 05:48 UTC by fraciah

# Description

Implement custom dropdown in users modal

# Screenshot
<img width="1191" alt="Screenshot 2024-09-24 at 08 44 49" src="https://github.com/user-attachments/assets/b806d5e1-2172-4860-a724-6ce1fd650b83">

2024-09-24 09:21 UTC, ReaganCn requested changes

2024-09-24 09:21 UTC, ReaganCn commented on libs/elements/layout/convs-mgr/custom-components/src/lib/components/custom-dropdown/custom-drop-down.component.scss
> +  width: 330px;
width is already set to 100% in the class .dropdown-options, which is more responsive

2024-09-24 09:21 UTC, ReaganCn commented on libs/elements/layout/convs-mgr/custom-components/src/lib/components/custom-dropdown/custom-drop-down.component.scss
> +  height: 100px;
From the screenshot, you need to double the height so that it can be more intuitive

2024-09-24 11:52 UTC, fraciah commented on libs/elements/layout/convs-mgr/custom-components/src/lib/components/custom-dropdown/custom-drop-down.component.scss
> +  width: 330px;
Without the width the options overflow:

<img width="1367" alt="Screenshot" src="https://github.com/user-attachments/assets/fd59d876-d4c4-484e-8532-13fee3935bb6">

2024-09-25 08:49 UTC, ReaganCn approved these changes

2024-09-25 08:49 UTC, merged