🎨{ refactor} Block delete#14
italanta/elewa pull request #107
Opened 2022-10-21 08:26 UTC by CarolGitonga

# Description

This feature has been implemented by removing the block from the StoryBlocksStore. A clock event is added to remove a particular block

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #14, 
## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Screenshot (optional)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-27 06:12 UTC, ReaganCn requested changes
Good work. I think you have updated more files that needed to resolve your issue. This might cause merge conflicts or revert some features on the main branch. Treat this as priority and clean up. Sync the changes with main and only update the files required to solve your issue.
Have a look at other changes requested.

2022-10-27 06:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { StoryBlocksStore } from '@app/state/convs-mgr/stories/blocks';
Properly order imports. Follow the order angular core, rxjs, services, models, components
Also I dont see there lodash is used, you can remove it and any other unused import

2022-10-27 06:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +
Remove the extra spacing and apply proper indentation

2022-10-27 06:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +
Also here

2022-10-27 06:12 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/convl-page.module.ts
> +    FontAwesomeModule
Remove FontAwesomeModule import. We dont need it

2022-10-27 06:12 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +  menu = faBars;
Also remove this icons. We changed the way we are implementing fontawesome icons

2022-10-27 06:12 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +import {faBars} from '@fortawesome/free-solid-svg-icons';
Remove unused imports

2022-10-27 06:12 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +              <fa-icon [icon]="menu" ></fa-icon>
Use the new implementation of icons. This will cause errors on the main branch

2022-10-27 06:12 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-page/convl-page.component.html
> +      <!-- <convl-sub-navbar [breadcrumbs]="breadcrumbs"><ng-content select=[subbar]></ng-content></convl-sub-navbar> -->
I dont think that this change is necessary with the issue you were working on. Sync changes from main and implement the delete function the way you have.

2022-10-31 09:51 UTC, CarolGitonga commented
Hi. @ReaganCn . I have made the changes requested

2022-11-08 12:17 UTC, IanOdhiambo9 requested changes
Hello,
I need you to walk me through this, when you're available schedule a quick call.

Also, do not comit your package-lock.json

2022-11-17 14:01 UTC, closed without merging