feat: create a bot card feature
italanta/elewa pull request #110
Opened 2022-10-24 09:29 UTC by kelvinmburu

This feature has been implemented by adding a card with a modal on the home screen. The card allows users to create a new bot if they don't have one.

Issue solved: https://github.com/italanta/elewa/issues/72

Fixes # (issue) - Fixes #72 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (Before and After)
## Before
<img width="1420" alt="elewa_b" src="https://user-images.githubusercontent.com/72970552/197493911-706709ac-3ad9-481c-beaf-e5096bc7d690.png">

## After
![elewa](https://user-images.githubusercontent.com/72970552/197492573-592d9f79-df87-4c84-bc14-677f46910313.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-26 14:16 UTC, kelvinmburu commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.ts
>      this.stories$ = this._stories$$.get();
@Lucywambui Does the requested change have to do with indentation and removing the extra ','?

2022-10-28 12:15 UTC, kelvinmburu commented
I've implemented the changes requested

2022-11-01 08:04 UTC, IanOdhiambo9 requested changes
Resolve conflicts on this branch by merging main into your branch.

2022-11-01 10:07 UTC, kelvinmburu commented
@IanOdhiambo9 Conflict resolved

2022-11-01 11:56 UTC, IanOdhiambo9 requested changes
Great!.
Your sidemenu appears to be different from the one on main, can you check?

2022-11-01 16:14 UTC, kelvinmburu commented
@IanOdhiambo9 By the time I made the PR, I hadn't pulled the new changes done on the side menu to my branch

2022-11-15 07:37 UTC, IanOdhiambo9 requested changes
Resolve conflicts

2022-11-15 07:37 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.html
> +    </mat-card>
This card should appear if the user has no stories yet!!

2022-11-28 05:20 UTC, closed without merging