:sparkles: Edit a Bot #103
italanta/elewa pull request #113
Opened 2022-10-26 03:02 UTC by AnnaL001

# Description

Adds a feature that allows for editing of a bot's details; name and description.  

Features added:
- [X] Edit bot form opens when the mode is "Edit Mode" with the specified title and submit button text.
- [X] Edit bot form is populated with the current bot details when the dialog is opened.
- [X] Changes to bot details are saved when clicking the button with the text "Update Bot".

Fixes #103.

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# Screenshot 
![Screenshot from 2022-10-26 05-13-02](https://user-images.githubusercontent.com/43697008/197922443-d5eb5915-c6e5-4422-853e-52839c41968a.png)

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-11-01 08:20 UTC, IanOdhiambo9 requested changes
Please find time to schedule a call with me to go over this together.

2022-11-01 08:20 UTC, IanOdhiambo9 commented on apps/conv-learning-manager/src/app/app.module.ts
Please gitignore your environments

2022-11-02 08:55 UTC, AnnaL001 commented on apps/conv-learning-manager/src/app/app.module.ts
Change has been made

2022-11-02 08:55 UTC, AnnaL001 commented on apps/conv-learning-manager/src/main.ts
Change has been made

2022-11-08 11:40 UTC, IanOdhiambo9 approved these changes
Good Job

2022-11-08 11:40 UTC, merged