:sparkles: Delete bot #104
italanta/elewa pull request #114
Opened 2022-10-26 13:07 UTC by LemmyMwaura

# Description

Deletes a bot as per the specification. Ref(#104)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot (63)](https://user-images.githubusercontent.com/20738858/198033635-f340a7f1-e168-41da-8c0f-4605b9bd0bbf.png)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-11-01 08:33 UTC, IanOdhiambo9 requested changes
Please find time and schedule a call with me to go over this. But good job so far.

2022-11-01 08:33 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.ts
> +import { DeleteBotModalComponent } from '../../modals/delete-bot-modal/delete-bot-modal.component';
Order of imports
@angular imports go first

2022-11-01 08:33 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +}
Restrict ::ng-deep with a local class otherwise the styles will leak to other dialogs.

eg ::ng-deep .my-page-class .delete-dialog-container .mat-dialog-container {}

2022-11-01 08:33 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +@import '_variables.scss';
No need to import _variables.scss. It's already imported in the main app stylesheet.

2022-11-01 08:33 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +@import 'libs/elements/theming/common.theme.scss';
No need for this as well

2022-11-01 08:33 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/services/new-story.service.ts
> +  }
You should only close the dialog when the remove operation was successful, for this you'll need to subscribe to the remove function and when it completes call the dialog close method, otherwise throw a toast that notifies the user delete was not successful.

2022-11-01 09:31 UTC, LemmyMwaura commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +}
The .delete-dialog-container class is specifically set on this modal only using the panel class attribute in the open dialog method. It acts as the restrictor class in this case.

2022-11-01 09:53 UTC, LemmyMwaura commented
Implementing the changes at the moment. Will schedule a session. Thanks

2022-11-03 08:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.ts
> +import { DeleteBotModalComponent } from '../../modals/delete-bot-modal/delete-bot-modal.component';
fixed the imports

2022-11-03 08:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +@import '_variables.scss';
removed

2022-11-03 08:53 UTC, LemmyMwaura commented on libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss
> +@import 'libs/elements/theming/common.theme.scss';
fixed. Although the theme is required, so still imported

2022-11-03 08:54 UTC, LemmyMwaura commented on libs/features/convs-mgr/home/src/lib/services/new-story.service.ts
> +  }
fixed, implemented as described

2022-11-07 06:40 UTC, IanOdhiambo9 approved these changes

2022-11-07 06:46 UTC, merged