🐛 🎨 Icons are not properly rendering-made change to render properly
italanta/elewa pull request #116
Opened 2022-10-27 08:24 UTC by Nyash-Mauro

# Description

Some Icons were missing i.e the search and bot menu they were not being rendered correctly. I added material icons to generate the icons and be displayed them correctly.

ref #115 
This change fixes issue ref#115

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
<img width="769" alt="icons-shwing" src="https://user-images.githubusercontent.com/68531415/198230709-806b92f7-6684-4354-87fb-db39bd0f43ed.PNG">

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2022-10-27 08:58 UTC, Nyash-Mauro commented
<img width="853" alt="search" src="https://user-images.githubusercontent.com/68531415/198240519-27169660-a8f7-4865-9d18-3104c2a7b2f7.PNG">
This is the final change

2022-10-27 09:21 UTC, Nyash-Mauro commented
<img width="954" alt="final-icons" src="https://user-images.githubusercontent.com/68531415/198245559-76629669-2574-414e-a42a-67102eb02b52.PNG">
THis is the site after removal of the font awesome icon that was not being used and doesn't exist in the design soecification

2022-11-01 08:44 UTC, IanOdhiambo9 requested changes

2022-11-01 08:44 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html
> +      </button>
Please change this icon to: "i class="fas fa-ellipsis-v""

2022-11-01 08:44 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.html
> +  </i>
Just use i class="fas fa-search" and flip with CSS to match design and color

2022-11-01 08:44 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts
>        botDesc: ['']
why is this removed?

2022-11-01 12:10 UTC, IanOdhiambo9 approved these changes

2022-11-01 12:10 UTC, merged