💄 {refactor} Created Bot Choose file input  #120
italanta/elewa pull request #127
Opened 2022-11-08 07:09 UTC by faisoabdirisak

# Description

Edited Choose bot file input to the required design.
Redesigned the create modal.

Fixes # (issue) -#120

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

![Screenshot (750)](https://user-images.githubusercontent.com/91128983/200497483-a9ede83e-1575-45c2-a4e2-a68d9dfe822d.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-11-08 12:02 UTC, IanOdhiambo9 requested changes
Find time to schedule a brief call so I can guide you on a strategy to do this.

2022-11-08 12:02 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/home/src/lib/services/new-story.service.ts
> +  image:false;
??

2022-11-11 04:14 UTC, faisoabdirisak commented on libs/features/convs-mgr/home/src/lib/services/new-story.service.ts
> +  image:false;
done all the changes

2022-11-15 07:15 UTC, IanOdhiambo9 requested changes
Your PR is okay, the updates look good however there are files you've committed that should not be pushed. package.json, package-lock.json, vscode/settings.json, main.ts and your git ignore.

2022-11-15 07:15 UTC, IanOdhiambo9 commented on .vscode/settings.json
> +}
Don't push this

2022-11-15 07:15 UTC, IanOdhiambo9 commented on apps/conv-learning-manager/.gitignore
> +src/environments/*
Don't push this as well

2022-11-15 07:15 UTC, IanOdhiambo9 commented on apps/conv-learning-manager/src/main.ts
>  }
Don't push this as well

2022-11-22 05:54 UTC, closed without merging