🔀 🤖 👨 ✨  Enable user to talk to agent - #1
italanta/elewa pull request #169
Opened 2022-12-01 13:08 UTC by ReaganCn

# Description

This PR includes implements a way for the user to be able to communicate with the agent. Processes the incoming message from the end user and updates it to the messages collection with the tag "toAgent".

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-05 08:35 UTC, jrosseel requested changes

2022-12-05 08:35 UTC, jrosseel commented on apps/conv-lm-backend/src/app/bot/whatsapp-channel/whatsapp-send-message.function.ts
> +const handler = new WhatsAppSendOutgoingMsgHandler();
The naming here is a bit confusing. I expect a path "'orgs/{orgId}/end-users/{endUserId}/messages/{id}'" to be channel agnostic.

So it should just be SendOutgoingMsg

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +          nextBlock = await bot.getNextBlock(message, endUser.id);
Should this be determined from the message or the cursor?

The issue with determining from the message is that it's more error prone. E.g. if I go back and click a button where I already clicked the other option, I will still resolve that message

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +          await bot.sendTextMessage("Chat has been paused", message.endUserPhoneNumber);
Add TODO: resolve paused flow

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +  private async _reply(bot: BotEngineMainService, endUser: EndUser, sideOperations: Promise<any>[], nextBlock: StoryBlock, message: Message)
How do you guard against endless loops?

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +  protected __injectVariable(outgoingText: string, dataSource: any): string
Move to seperate file/function

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +    botMessage.direction = MessageDirection.TO_END_USER;
Can bot.reply handle this direction setting?

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/io/block-to-message-parser.class.ts
> +    });
Object returns like this (inside an arrow fn) can be simplified

block.options.map((option) =>
    ({
        optionId: option.id,
        optionText: option.message,
        optionValue: option.value
    }));

2022-12-05 08:35 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts
> +  async resolveFutureBlock(currentBlock: StoryBlock, orgId: string, currentStory: string, msg?: Message, endUserId?: string)
Comments!

2022-12-05 08:35 UTC, jrosseel commented on libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts
> +export enum MessageDirection
Add comment + Use numeric values for the enum values (to save DB space especially sicne this will be on every message)

2022-12-06 13:26 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +    botMessage.direction = MessageDirection.TO_END_USER;
It cannot, because here we convert the block to our standardized message and save it in the 'messages' collection. So this message is not being sent to the end user. Just saved in the database so that it can also be picked up by another chat app e.g. the farmbetter app

2022-12-06 13:33 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts
> +    if (latestCursor.futureBlock) {
It was for when I was saving the current and the next block in the cursor. But now its not needed. I have removed it.

2022-12-06 13:34 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts
> +  async resolveFutureBlock(currentBlock: StoryBlock, orgId: string, currentStory: string, msg?: Message, endUserId?: string)
I have removed the usage of this function entirely. I dont need it now.

2022-12-06 13:38 UTC, ReaganCn commented on libs/functions/bot-engine/whatsapp/src/lib/io/incoming-message-parser/whatsapp-api-incoming-message-parser.class.ts
>      const newMessage: TextMessage = {
The id is set to a timestamp when the message is being saved to the database. But I will set it to here because we loose time between receiving the message and saving it.

2022-12-06 13:38 UTC, ReaganCn commented on libs/functions/bot-engine/whatsapp/src/lib/io/incoming-message-parser/whatsapp-api-incoming-message-parser.class.ts
>      const baseMessage: QuestionMessage = {
The id is set to a timestamp when the message is being saved to the database. But I will set it to here because we loose time between receiving the message and saving it.

2022-12-08 08:15 UTC, merged