🔀 ♻️ Implement a specific interface for 'playing' through the stories
italanta/elewa pull request #210
Opened 2022-12-19 06:49 UTC by ReaganCn

# Description

Created `BotEnginePlay` and implement an interface thats only responsible for playing through the stories. So that we can call `bot.play` in the Bot Engine Manager

## Type of change

- [x] Refactor

2022-12-21 09:09 UTC, jrosseel requested changes

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +    sideOperations.push(this.__move(newPosition, endUser.id));
Don't nest actions.

const moveToNext = this.__move...
sideOperations.push(moveToNext)

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +      sideOperations.push(this._saveBlockAsMessage(currentBlock, endUser.id));
Same, don't nest operations

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +      currentBlock.message = variableInjectorService.injectVariableToText(currentBlock.message, endUser);
Naming could be better

mailMergeVariables

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +      sideOperations.push(this.__move({ currentBlock: currentBlock }, endUser.id));
No nested actions

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +  private async __move(newPosition: EndUserPosition, endUserId: string): Promise<EndUserPosition>
Should be batched in mid-term for performance

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine.main.ts
> +export class BotEngineMain
Duplication of the bot play?

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine.main.ts
> +    if (message.type == MessageTypes.AUDIO || message.type == MessageTypes.VIDEO || message.type == MessageTypes.IMAGE) {
Should be done at Message parser level. You can have subtypes of MessageParser which is fileMessage, which does this

Then FileMessage is next inherited by the specific file types i.e. AudioMessage, ...

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/bot-engine.main.ts
> +    if (message.type == MessageTypes.AUDIO || message.type == MessageTypes.VIDEO || message.type == MessageTypes.IMAGE) {
So save method in this subclass does
{
 fileMessage.url = ...
 return super.save(fileMessage, endUserId)
}

2022-12-21 09:09 UTC, jrosseel commented on libs/functions/bot-engine/main/src/lib/services/chat-commands/chat-commands-manager.service.ts
> +    this.orgId =  _activeChannel.channel.orgId
; at the end

2023-01-16 08:29 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +    while (currentBlock.type === StoryBlockTypes.TextMessage || currentBlock.type == StoryBlockTypes.Image) {
Storyblocks just have the property `type`, whose type is `StoryBlockTypes` and  blocks mainly set it to textmessage, image, video etc. There is also 'IO' and 'Input' in storyblock types in addition to the different block types.  Perhaps we add another property to storyblocks which shows whether its an input or output block?

2023-01-20 14:57 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts
> +  private async __move(newPosition: EndUserPosition, endUserId: string): Promise<EndUserPosition>
It is pushed to sideOperations to be resolved later. Though an optimization of how we handle these types of operations can be done

2023-04-04 08:16 UTC, closed without merging