:robot: feat: WhatsApp bot inteprets outgoing LocationMessageBlock
italanta/elewa pull request #232
Opened 2023-01-05 18:13 UTC by kelvinmburu

# Description

The changes for this PR address issue #208 which relates to the backend (WhatsApp bot engine)

This PR fixes #208 .

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot

# How Has This Been Tested?

- [x] Test clear conversation of the outgoing message to a standardized message with comments
- [ ] The message should be received on WhatsApp as a location (Yet to test)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2023-01-10 06:49 UTC, ReaganCn commented
Good Morning Kelvin,

Good work so far but for backend tasks you will also need to write unit tests for the specific function implemented. You can refer to this [PR](https://github.com/italanta/elewa/pull/222/files) to see how I have written them and where they are located. I know this was not included in the initial issue description but will add it.

Thank you.

2023-01-10 08:12 UTC, kelvinmburu commented
Thanks. Let me add the test

2023-01-20 17:14 UTC, ReaganCn requested changes
Good work. But I dont understand why we are editing front end files and it is a backend issue. Also you need to write tests so that we can see if it works

2023-01-20 17:14 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html
>  <!-- edited the search -->
I dont understand why we are editing this file and it is a backend issue

2023-01-20 17:14 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss
>    margin-left: 24em;
Also this.

2023-01-20 17:14 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.ts
>  import { StoriesStore } from '@app/state/convs-mgr/stories';
Also this.

2023-01-20 18:54 UTC, kelvinmburu commented on libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html
>  <!-- edited the search -->
Hello @ReaganCn, There was a mixup when I was making the PR for this backend issue. The commit for issue #72 appeared on this PR which wasn't supposed to happen.

2023-01-23 08:03 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html
>  <!-- edited the search -->
It's okay. You can make the changes and push them

2023-02-16 05:42 UTC, closed without merging