🎨   Implemented a multiple input block
italanta/elewa pull request #249
Opened 2023-01-18 08:42 UTC by conceptacherono

# Description

As a user you should be able to add a block that accepts multiple inputs.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Screenshot (optional)
![multiple-input-block](https://user-images.githubusercontent.com/91899034/213123520-5cd82b4a-0ce1-4c14-a16d-73d57b6dcdda.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2023-01-20 17:05 UTC, ReaganCn requested changes
Please check my comments. Otherwise, good work

2023-01-20 17:05 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.html
> +              Add Option
Use multi-lang

2023-01-20 17:05 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.html
> +      New List
Also here. Use multi-lang

2023-01-20 17:05 UTC, ReaganCn commented on libs/model/convs-mgr/stories/blocks/messaging/src/lib/multiple-input-message-block.interface.ts
> +export interface MultipleInputMessageBlock extends StoryBlock
Explain what a multiple input message block does

2023-01-20 17:05 UTC, ReaganCn commented on libs/model/convs-mgr/stories/blocks/messaging/src/lib/multiple-input-message-block.interface.ts
> +  tag?: string;
What does `tag` and `context` do???

2023-01-23 07:56 UTC, conceptacherono commented on libs/model/convs-mgr/stories/blocks/messaging/src/lib/multiple-input-message-block.interface.ts
> +  tag?: string;
I have implemented these changes

2023-01-25 13:26 UTC, ReaganCn approved these changes

2023-01-25 13:26 UTC, merged