🎨 🔢 A user can be able to delete options from blocks that accepts multiple options
italanta/elewa pull request #253
Opened 2023-01-20 09:48 UTC by conceptacherono

deleting inputs

# Description
A user can  be able to delete a option from a block that accepts multiple options. These includes question blocks and list blocks.

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![deleting](https://user-images.githubusercontent.com/91899034/213665580-c697f929-fcc9-483d-b940-7bfddb3418cb.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings

2023-01-20 17:10 UTC, ReaganCn requested changes
Good work. Just one small thing

2023-01-20 17:10 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts
> +    anchor: "Left",
I dont think placing the anchor on the left side is a good idea. It is not intuitive. You can instead place the delete option icon on the left

2023-01-23 07:55 UTC, conceptacherono commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts
> +    anchor: "Left",
I have implemented this change.

2023-01-24 05:36 UTC, ReaganCn approved these changes

2023-01-25 12:05 UTC, merged