🧱 🖊️  Open ended Qstns edit forms
italanta/elewa pull request #289
Opened 2023-02-09 13:13 UTC by LemmyMwaura

# Description
Add Open ended Qstns block edit form. depends on #288 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-02-13 06:51 UTC, ReaganCn requested changes

2023-02-13 06:51 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.html
> +    <span class="title">Open-Ended Question</span>
Use multi-lang.

2023-02-14 11:31 UTC, IanOdhiambo9 approved these changes

2023-02-16 05:26 UTC, ReaganCn approved these changes

2023-02-16 05:29 UTC, merged