🧱 🪝 Webhook edit forms
italanta/elewa pull request #294
Opened 2023-02-10 12:13 UTC by LemmyMwaura

# Description

Adds the Webhook Edit Form. depends on #288 and #289

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot (6)](https://user-images.githubusercontent.com/20738858/218089500-785140d7-8b9d-4791-987a-915c0f69dd0b.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

2023-02-13 06:53 UTC, ReaganCn requested changes

2023-02-13 06:53 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/webhook-edit/webhook-edit.component.html
> +    <span class="title">Webhook Edit Block</span>
Use multi-lang

2023-02-13 06:53 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/webhook-edit/webhook-edit.component.ts
> +import { Observable } from 'rxjs';
Check order of imports

2023-02-14 11:35 UTC, IanOdhiambo9 approved these changes

2023-02-16 05:27 UTC, ReaganCn approved these changes

2023-02-16 05:38 UTC, merged