🧱 📝 Audio location video image edit forms
italanta/elewa pull request #295
Opened 2023-02-10 13:49 UTC by LemmyMwaura

# Description

Adds the Audio, Location, Video and Image Edit Form. depends on #288, #289 and #294
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![Screenshot (7)](https://user-images.githubusercontent.com/20738858/218107879-3f308a83-bec5-4585-8cfb-a9bca6963ea5.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

2023-02-13 06:55 UTC, ReaganCn requested changes

2023-02-13 06:55 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/audio-input-block-edit/audio-input-block-edit.component.html
> +    <span class="title">Audio Input Block</span>
Use multi-lang

2023-02-13 06:55 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/image-input-block-edit/image-input-block-edit.component.html
> +    <span class="title">Image Input Block</span>
Also here

2023-02-13 06:55 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/location-input-block-edit/location-input-block-edit.component.html
> +    <span class="title">Location Input Block</span>
Also here

2023-02-13 06:55 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/video-input-block-edit/video-input-block-edit.component.html
> +    <span class="title">Video Input Block</span>
Also here

2023-02-14 11:40 UTC, IanOdhiambo9 requested changes

2023-02-14 11:40 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/webhook-edit/webhook-edit.component.ts
> +import { Observable } from 'rxjs';
order of imports

2023-02-14 11:40 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/webhook-edit/webhook-edit.component.ts
> +    console.log(this.form)
remove

2023-02-14 11:40 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.scss
>  input {
code formating

2023-02-14 11:40 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/webhook-block/src/lib/components/webhook-block/webhook-block.component.html
>  		<form [formGroup]="webhookForm" fxLayout="column" fxLayoutALign="start" fxFlex>
code formating - 2 spaces

2023-02-14 12:17 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/webhook-edit/webhook-edit.component.ts
> +    console.log(this.form)
fixed

2023-02-14 12:18 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.scss
>  input {
github indentation issue

2023-02-16 05:27 UTC, ReaganCn approved these changes

2023-02-16 05:28 UTC, ReaganCn approved these changes

2023-02-16 05:57 UTC, ReaganCn approved these changes

2023-02-27 06:18 UTC, IanOdhiambo9 approved these changes

2023-02-27 07:29 UTC, merged