:art: :bricks: Improvements on delete block #241
italanta/elewa pull request #312
Opened 2023-02-20 05:59 UTC by AnnaL001

# Description
Improves the delete block functionality by marking its connections to and from, as deleted and removing them from the database.

Fixes #241 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-21 08:39 UTC, ReaganCn requested changes
Good work. Just some minor changes

2023-02-21 08:39 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { NewStoryService } from 'libs/features/convs-mgr/stories/home/src/lib/services/new-story.service';
Use domain imports: `@app/import-path`

2023-02-21 08:39 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
> +
It's best if this function is in the block connections store

2023-02-21 08:39 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
> +        });
No need to mark the connection as deleted, if its going to be deleted from the store immediately after

2023-02-22 05:55 UTC, AnnaL001 commented on libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
> +        });
Has been removed

2023-02-22 05:56 UTC, AnnaL001 commented on libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
> +
Has been transferred to block connections store and block connections service

2023-02-22 05:57 UTC, AnnaL001 commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { NewStoryService } from 'libs/features/convs-mgr/stories/home/src/lib/services/new-story.service';
The import has been removed

2023-02-22 06:01 UTC, ReaganCn requested changes
Good job, just one import fix

2023-02-22 06:01 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { BlockConnectionsService } from '@app/state/convs-mgr/stories/block-connections';
Domain imports should come before local @app before '../../imports'

2023-02-22 07:01 UTC, AnnaL001 commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { BlockConnectionsService } from '@app/state/convs-mgr/stories/block-connections';
Done

2023-02-22 08:24 UTC, ReaganCn approved these changes

2023-02-22 08:24 UTC, merged