:art:  Improvements on image/video block, adding spinner/loader when file is being uploaded
italanta/elewa pull request #315
Opened 2023-02-20 13:15 UTC by aboiyon

# Description.
A user will see a loader after adding a video/image attachment to the video/image block so that they can tell that the process of uploading is taking place

Fixes #304 

## Type of change
Front-end design changes 

# Screenshot 
 
[Elewa Conversational Learning Manager (2).webm](https://user-images.githubusercontent.com/91332113/230777834-98185aa8-30d7-40aa-9d5f-3cda2b322aa9.webm)

- [ ] I have performed a self-review of my code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings

2023-02-23 14:24 UTC, ReaganCn requested changes
Good work. Please attach a short video on uploading a video on the video block

2023-02-27 07:50 UTC, ReaganCn requested changes
Good work, just some minor changes

2023-02-27 07:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.scss
> +
To avoid repetition move this spinner class and its animation to the app level styles.scss

2023-02-27 07:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.scss
> +
Once you move it, we wont need this.

2023-03-20 10:07 UTC, LemmyMwaura requested changes
Still some changes to make. Please make sure you can successfully upload a file

2023-03-20 10:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
>      }
This is not necessary as angularFireStorage handles the upload. You can set the isloading property to false once the downloadurl is returned.

2023-03-20 10:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
> +
There's two file uploads currently happening. One through the angularfirestoreservice injected and another through the video upload service. Use one

2023-04-17 08:31 UTC, njoroge-jane commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
> +
@aboiyon good job! kindly work on this last minor change.

2023-04-18 12:49 UTC, LemmyMwaura requested changes

2023-04-19 05:43 UTC, LemmyMwaura approved these changes

2023-04-24 09:03 UTC, ReaganCn approved these changes

2023-04-24 09:04 UTC, merged