:recycle:  Move text area field to a text message component for reuse
italanta/elewa pull request #318
Opened 2023-02-22 08:35 UTC by aboiyon

# Description

This is a refactor where the messages of story blocks are moved to a separate component TextMessageComponent. This will ensure reusability across the project where we have 'textarea'.

Fixes #316 

# Screenshot

2023-02-22 08:59 UTC, ReaganCn requested changes
Good job, just some minor cleanup and you're good

2023-02-22 08:59 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.html
> +
Remove unused commented code

2023-02-22 08:59 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.html
> +
Same here. Do the same for all the commented out code in this PR

2023-02-23 14:19 UTC, ReaganCn requested changes
I cannot see the code for the TextMessageComponent

2023-02-23 21:05 UTC, aboiyon commented
> I cannot see the code for the TextMessageComponent

https://github.com/italanta/elewa/pull/318/commits/da589c48e68a6282596d7231eb87730c5e80bea1 here is the code

2023-02-27 06:12 UTC, ReaganCn requested changes
Please make sure that the text message component is in the path specified in the issue.
It should be in: 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/34684844/221488157-3fcb2297-edf3-4e80-b25d-84564a20f6c3.png">

2023-03-15 14:00 UTC, ReaganCn approved these changes

2023-03-19 13:52 UTC, closed without merging