:art: Set number of characters in question and list block
italanta/elewa pull request #319
Opened 2023-02-22 13:12 UTC by aboiyon

# Description
Setting maximum characters so that a user can only enter a specific number of characters in the question and list blocks so that API limit is not surpassed. 

Fixes #302 

## Type of change
perf

Please delete options that are not relevant

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-02-23 13:56 UTC, ReaganCn requested changes
Good attempt. There are still some things from the acceptance criteria you have not addressed. Also some minor requests

2023-02-23 13:56 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.ts
> +    if (this.listItems.length < 10)
Save this number to a const

2023-02-23 13:56 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts
> +    if (this.options.length < 3) {
Same here

2023-03-20 10:12 UTC, LemmyMwaura commented
Closing in favour of #321

2023-03-20 10:12 UTC, closed without merging