🎨🔢 Set limit to number of characters and possible options on question and list block options
italanta/elewa pull request #321
Opened 2023-02-23 09:17 UTC by royokite

# Description

This pull request is made in part to handle number of options and character limit on the question and list blocks.

For the list block:
- A maximum of 10 options with a maximum of 24 characters each.

For the question block
- A maximum of 3 options with a maximum of 20 characters each

Fixes [#302] 🎨 🔢 As a user I should be able to see the number of characters in question and list block options

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot (372)](https://user-images.githubusercontent.com/56071589/220865187-e61e88ac-0aef-4a6c-a1f4-c6be00768259.png)

# How Has This Been Tested?

- Type into option input and evaluate input size set to 20 for question block and 24 for list block.
- Created a question block to test possible options and the limit works at 3.
- Created a list block to test possible options and the limit works at 10.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-23 13:54 UTC, ReaganCn requested changes
Good job. Just some minor changes

2023-02-23 13:54 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.html
> +          maximum characters reached
Please use multi-lang. Have a look at the below from the `login.component.html`
<img width="645" alt="image" src="https://user-images.githubusercontent.com/34684844/220926604-afea2ba4-e175-4375-8140-0ce57c2b59b2.png">

The translations are added in the files `en.json` and `fr.json`

2023-02-23 13:54 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.ts
> +    if (this.listItems.length < 10) this.listItems.push(this.addListOptions());
Save this number to a `const`

2023-02-23 13:54 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.html
> +            class="input" [charMaxlength]=20></app-option-input-field>
Same here

2023-02-23 13:54 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts
> +    if (this.options.length < 3) this.options.push(this.addQuestionOptions());
Same here

2023-02-23 16:48 UTC, royokite commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts
> +    if (this.options.length < 3) this.options.push(this.addQuestionOptions());
Made all the requested changes. @ReaganCn

2023-02-27 06:17 UTC, ReaganCn approved these changes

2023-02-28 13:50 UTC, merged