#308 🤏 Add pinch to zoom functionality to story editor
italanta/elewa pull request #326
Opened 2023-02-23 13:07 UTC by lilmithi

# Description

- This pull request implements the pinch to zoom functionality on the story editor frame.
- The functionality has been implemented via a **custom directive** that can be found in the  "libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame" folder path
- The zoom-in functionality has a maximum scale of 200% while the zoom-out functionality has a minimum scale of 50%.
- The editor frame listens for a 'wheel' event via the HostListener upon which it automatically updates the frameZoom value.

Fixes #308

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
# ScreenRecord (gif)
![Elewa Conversational Learning Manager (1)](https://user-images.githubusercontent.com/104300169/220914800-ea442a3e-b426-4d61-abbb-790e0347ced3.gif)

# How Has This Been Tested?
- [ ] This has been tested with both the Firefox and Chrome browser and works as expected.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-23 13:07 UTC, lilmithi commented
@ReaganCn, @LemmyMwaura awaiting review

2023-02-23 14:12 UTC, ReaganCn requested changes
Good job!! Please address the requested changes

2023-02-23 14:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.ts
> +    console.log("Level ",level);
Please remove this console.log

2023-02-23 14:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/app-pinch-zoom.directive.ts
> +}
Move this directive to `editor/src/lib/directives`

2023-02-23 14:12 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/app-pinch-zoom.directive.ts
> +import { clamp } from 'lodash';
Move lodash import to be the first import

2023-02-23 14:50 UTC, lilmithi commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.ts
> +    console.log("Level ",level);
@ReaganCn Change has been implemented awaiting review

2023-02-23 15:09 UTC, lilmithi commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/app-pinch-zoom.directive.ts
> +import { clamp } from 'lodash';
@ReaganCn All requested changes have since been implemented awaiting review

2023-02-27 06:22 UTC, ReaganCn approved these changes

2023-02-28 13:54 UTC, merged