#307 Make the story editor workspace endless on scroll to the right and bottom
italanta/elewa pull request #327
Opened 2023-02-24 10:16 UTC by jobkarani

# Description

This pull request makes the story editor workspace endless on scroll and bottom. To achieve this I had to install the **ngx-infinite-scroll** package.

Fixes #307

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
[Elewa Conversational Learning Manager (5).webm](https://user-images.githubusercontent.com/53146890/221153081-61922a73-8e16-4bcd-b5e6-6d7c1085714c.webm)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 06:30 UTC, ReaganCn requested changes
Good job. Just some few changes

2023-02-27 06:30 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.ts
> +    console.log(event)
Remove this console.log

2023-02-27 06:30 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts
> +import { InfiniteScrollModule } from 'ngx-infinite-scroll';
Check order of imports. External imports should come before internal imports. 'ngx-infinite-scroll' should come after angular imports and before internal imports

2023-02-27 07:26 UTC, jobkarani commented
@ReaganCn the requested changes have been implemented. Please review again.

2023-02-27 07:33 UTC, ReaganCn approved these changes

2023-03-03 11:38 UTC, ReaganCn approved these changes
Good work

2023-03-03 11:39 UTC, merged