#320 Semi-Collapse Sidenav When Portal Is Open
italanta/elewa pull request #328
Opened 2023-02-26 14:07 UTC by lilmithi

# Description

- This pull request implements the semi-collapse functionality of the Sidenav when portal is open (When one clicks the edit button on a block).
- The functionality has been implemented via the **SidemenuToggleService** found in "libs/services/sidemenu-toggle.service.ts" directory.
- The service implements an **Observable** in the form of a **BehaviorSubject** which tracks any changes in the state of the side-nav.
- The convl-sidemenu component subscribes to the observable any any change is reflected upon automatically.
- The side-nav automatically collapses on clicking the block form edit button as shown in the recording below.

Fixes #320 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# ScreenRecording (gif)
![Elewa Conversational Learning Manager](https://user-images.githubusercontent.com/104300169/221415341-d65a6124-6428-49a9-a7dd-4421822eb0b4.gif)

# How Has This Been Tested?

- [ ] Tested against both Firefox and Chrome browsers and works as expected.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-26 14:07 UTC, lilmithi commented
@ReaganCn @LemmyMwaura awaiting review

2023-02-26 18:12 UTC, LemmyMwaura requested changes
Make the necessary updates as you await a final review. Also, the service should be stored elsewhere, Have it in a providers folder inside the same module that holds the side menu.

2023-02-26 18:12 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +import { SidemenuToggleService } from '../../../../../../../services/sidemenu-toggle.service'
This path is too long, import from the alised path

2023-02-26 18:12 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +    this.sideMenu.expand.subscribe(v=>this.isExpanded=v)
v is too short of a name, use something self-explanatory e.g isOpen, isExpanded etc.

2023-02-26 18:12 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +    this.sideMenu.expand.next(!this.isExpanded)
Only call 'next' in the service you created (use methods).

2023-02-26 18:12 UTC, LemmyMwaura commented on libs/services/sidemenu-toggle.service.ts
> +  expand = new BehaviorSubject(true);
Use  `asObservable` to access this BehaviourSubject from elsewhere to prevent leaking its "observer side" out of the API. 

Essentially the 'expand' property should be private (ensures you only call next from this service) and have another property which is the Observable from this subject that you will subscribe to from elsewhere.

2023-02-26 18:16 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +    this.sideMenu.expand.subscribe(v=>this.isExpanded=v)
Unsubscribe from this subscription when the component unmounts to avoid memory leaks. Use Subsink `https://github.com/wardbell/subsink`, already installed.

2023-02-27 05:27 UTC, lilmithi commented
@LemmyMwaura @ReaganCn Requested changes have since been implemented

2023-02-27 08:03 UTC, LemmyMwaura requested changes
Almost done, Just a few fixes.

2023-02-27 08:03 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
>      this.menuToggled.emit();
This menuToggled event is no longer necessary (was removed). Remove it and also remove the listener from the parent.

2023-02-27 08:03 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/providers/sidemenu-toggle.service.ts
> +  observable$ = this._expand.asObservable();
rename this to menuStatus$

2023-02-27 08:52 UTC, lilmithi commented
@LemmyMwaura changes implemented awaiting review

2023-02-28 05:37 UTC, merged