Issue#336/ft video upload modal
italanta/elewa pull request #344
Opened 2023-03-09 15:41 UTC by Beulah-Matt

# Description

I have implemented a video modal with a 
-Title
-Name inputs
-A thumbnail image
-Radio check marks to select video resolution.

On clicking the play button  in the video block, you are redirected to this modal.
When you click on the thumbnail, a file explorer window is opened to select a video file  

Fixes #336
## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![videomodalpopup](https://user-images.githubusercontent.com/109944021/224075478-f1c4f8cf-268c-411f-b19e-fa925af54265.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-20 10:57 UTC, LemmyMwaura requested changes
Good job so far but still some updates to make 
- Some of the methods currently exist in both components, this can be better shared in a service. 
- At the moment I can select a video but I can't view it in the modal. 
- The modal is also not responsive. 
- The state of the selected does not persist into the block

2023-03-20 10:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/modals/video-block-modal/video-block-modal.component.ts
> +  modalOpen = true;
Don't conditionally render this, get the reference to this dialog and close it when the close button is clicked. 

docs -> https://material.angular.io/components/dialog/overview

2023-03-20 10:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/modals/video-block-modal/video-block-modal.component.ts
> +  constructor(private _videoUploadService: UploadFileService,
We need to inject the current video data if it does exist into the dialog. Also, check the docs for more info

2023-03-22 13:11 UTC, Beulah-Matt commented
@LemmyMwaura @ReaganCn please confirm if the current changes are what you had in mind?

2023-03-28 07:25 UTC, LemmyMwaura requested changes
The state of the selected video, still doesn't persist into the blocks. and theres's also some errors in the console.

2023-04-06 19:05 UTC, LemmyMwaura requested changes
Rebase(ing) has caused you to pile on commits that were already authored and committed. Please sort this out or create a new pr with only your commits

2023-04-07 12:46 UTC, closed without merging