Error prompt when i upload a wrong file format for media files #330
italanta/elewa pull request #347
Opened 2023-03-10 00:39 UTC by 23po

# Description

Created a reusable dialog box under libs/elements/layout/modals that is displayed when a user uploaded an unsupported media file.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # 330

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Video Link
[error modal vid.webm](https://user-images.githubusercontent.com/48943229/224193325-320e766f-9cbc-4836-92fc-d612b7ef0741.webm)

# How Has This Been Tested?

This runs on the development server

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-10 00:41 UTC, 23po commented
@ReaganCn @LemmyMwaura @IanOdhiambo9 please review

2023-03-20 12:40 UTC, LemmyMwaura requested changes
Just some minor fixes

2023-03-20 12:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +
Import from the aliased path

2023-03-20 12:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +    }
Use the error Modal

2023-03-20 12:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
> +
Import from aliased path

2023-03-20 12:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.ts
> +
Also here fix Import path.

2023-03-21 06:43 UTC, 23po commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +
fixed

2023-03-21 06:43 UTC, 23po commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
> +
fixed

2023-03-21 06:44 UTC, 23po commented on libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.ts
> +
fixed

2023-03-21 06:53 UTC, 23po commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +    }
fixed

2023-03-21 07:03 UTC, 23po commented
@LemmyMwaura issues have been fixed

2023-03-28 07:07 UTC, LemmyMwaura requested changes
- There's an issue with the feature. I can only check the file type once. After that, the modal doesn't show up. 
- Also if I encounter an error during upload the spinner never stops. 
- The open modal method since it's essentially the same in every file can be saved in a shared service and then we pass the dynamic values, such as title. Please use the FileStorage service.

2023-03-28 07:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.ts
> +this.block = this.block as ImageMessageBlock;
??

2023-03-28 07:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/convs-mgr-video-message-block.module.ts
> +import { ElementsLayoutModalsModule } from '@app/elements/layout/modals';
No need to import this module. Applies to the video message module also

2023-04-13 08:06 UTC, closed without merging