As a user i should be able to update my channel details after i publish a story #342
italanta/elewa pull request #373
Opened 2023-03-22 04:11 UTC by 23po

# Description

This PR makes it possible for a user to update their channel details after publishing a story.

Fixes #342

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Video
[screen-capture (4).webm](https://user-images.githubusercontent.com/48943229/226799978-f0e179db-b32c-4a80-a23a-53eaabf1f19c.webm)

 

# How Has This Been Tested?

This has been tested on the development server, and the changes observed to reflect on the db under channels

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-22 04:23 UTC, 23po commented
@LemmyMwaura @ReaganCn please review

2023-03-27 07:17 UTC, ReaganCn requested changes
Good first attempt. But there are still some changes that you need to address:
- Your code has a bug that will constatly update the details endlessly (endless loop). 
- There are some rendundacies which I have highlighted
- Finally your video needs to show everything from publishing the details when they dont exist to updating them.

2023-03-27 07:17 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +import { Story } from '@app/model/convs-mgr/stories/main';
Check order of imports. Domain imports should come before local imports

2023-03-27 07:17 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/components/shared-service.ts
> +  private _isPublished = new Subject<CommunicationChannel>();
Please use BehaviourSubject instead, and set the initial value to false

2023-03-27 07:17 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/providers/manage-channel-story-link.service.ts
> +
Remove this commented out code.

2023-03-27 07:17 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/providers/manage-channel-story-link.service.ts
> +
Also this

2023-04-17 08:45 UTC, njoroge-jane commented
@23po Kindly do make the requested changes and notify once done or if you might need more clarification or assistance.

2023-04-17 15:14 UTC, 23po commented
> @23po Kindly do make the requested changes and notify once done or if you might need more clarification or assistance.

sure

2023-05-05 08:43 UTC, LemmyMwaura commented
Closing this to avoid backlog

2023-05-05 08:47 UTC, 23po commented
hi @LemmyMwaura i am working on the issue

2023-05-05 08:52 UTC, LemmyMwaura commented
Please communicate if you need assistance.

2023-05-18 12:45 UTC, LemmyMwaura commented
Closing this for #473 (opened by the same user)

2023-05-18 12:45 UTC, closed without merging