💾 🎵 Save Audio Input Block Result As a Variable
italanta/elewa pull request #417
Opened 2023-04-13 08:16 UTC by JamesMGithire

# Description

This PR adds the ability to save the audio variable in the user's response and also a validation form.

Fixes ⚡https://github.com/italanta/elewa/issues/405

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-04-13 11-01-03](https://user-images.githubusercontent.com/105742325/231697273-e4d76214-dd5e-4db4-a10e-555a989cce3b.png)

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-04-14 09:34 UTC, LemmyMwaura requested changes
You need to update the function that creates this block with the new form fields

2023-04-17 05:00 UTC, JamesMGithire commented
@LemmyMwaura, The requested changes are complete. Kindly review.

2023-04-17 05:43 UTC, LemmyMwaura requested changes
Just a few changes left

2023-04-17 05:43 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/audio-validations/audio-validations.component.html
> +<div [formGroup]="variablesForm">
Since no validation is required for this block. This component should not be present

2023-04-17 13:44 UTC, LemmyMwaura approved these changes

2023-04-17 13:44 UTC, merged