:lipstick: :computer: Increase Side Screen Size
italanta/elewa pull request #458
Opened 2023-05-03 22:09 UTC by Michael-Otieno

# Description

I worked alone.

This pull request solves issue #450, whereby I have redesigned the Block List UI following the design's guidelines.

Fixes #450

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

https://user-images.githubusercontent.com/85155606/236060462-fcfc34f3-1690-4ea3-ad45-f7da64985748.mp4

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
-  [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-05-04 06:31 UTC, LemmyMwaura requested changes
Please check the issue again, The requirement is for the side screen to toggleable when active

2023-05-05 00:59 UTC, Michael-Otieno commented
Waiting for review @LemmyMwaura

2023-05-05 08:34 UTC, Michael-Otieno commented
> Please check the issue again, The requirement is for the side screen to toggleable when active

Waiting for review @LemmyMwaura

2023-05-05 08:51 UTC, LemmyMwaura requested changes
There are a few situations you haven't taken into account.
- What happens when I click the edit btn on a block while the side screen is closed? (should open the side screen and also open the portal).
- What happens when I close the side screen while the form portal is open/attached. (should also be closed)

2023-05-05 11:13 UTC, Michael-Otieno commented
> There are a few situations you haven't taken into account.
> 
> * What happens when I click the edit btn on a block while the side screen is closed? (should open the side screen and also open the portal).
> * What happens when I close the side screen while the form portal is open/attached. (should also be closed)

Updated PR. Waiting for review @LemmyMwaura

2023-05-05 12:28 UTC, LemmyMwaura requested changes
We have some performance concerns with the closing and opening. It lags while toggling this is because we're using ngIf. Challenge -> Try and see if you can optimize it.

2023-05-05 12:37 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { SideScreenToggleService } from 'libs/features/convs-mgr/stories/editor/src/lib/providers/side-screen-toggle.service';
use alised imports

2023-05-05 14:25 UTC, Michael-Otieno commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +import { SideScreenToggleService } from 'libs/features/convs-mgr/stories/editor/src/lib/providers/side-screen-toggle.service';
rectified

2023-05-05 19:05 UTC, LemmyMwaura approved these changes
Good Job 👍, I was hoping you'd use ngClass for the optimisation as it gives us more control over the design but I've switched it to that.

2023-05-05 19:10 UTC, merged