Issue#444 save open ended question as a variable
italanta/elewa pull request #469
Opened 2023-05-11 12:08 UTC by jeffoty

# Description

This pull request solves issue #444 that required me to create an edit panel for open ended questions.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
   
![image](https://github.com/italanta/elewa/assets/107908318/e1f8038c-0ce4-43bd-a8d8-83786ca64f27)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-12 06:17 UTC, LemmyMwaura requested changes
A regex field is not required for this block

2023-05-13 09:55 UTC, LemmyMwaura requested changes

2023-05-13 09:55 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/open-ended-question-block-form.model.ts
> +            "I'm afraid I didn't get that, could you send your pin again, please?",
Also, please remove it from here and add the fields required (min and max).

2023-05-13 15:41 UTC, jeffoty commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/open-ended-question-block-form.model.ts
> +            "I'm afraid I didn't get that, could you send your pin again, please?",
max and min validators added and regex validator removed.

2023-05-15 05:48 UTC, LemmyMwaura requested changes
Everything works as it should, Just a few minor changes left.

2023-05-15 05:48 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.html
> +      formControlName="message" />
Instead of an input let's reuse the `reusable text area` component.

2023-05-15 05:48 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.ts
> +  OpenEndedQuestionId: string;
No need for this property, (No need for any change on this component)

2023-05-15 05:48 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.ts
> +  }
Also here

2023-05-16 05:59 UTC, LemmyMwaura approved these changes

2023-05-16 06:00 UTC, merged