As a user i should be able to update my channel details after i publish a story   3
italanta/elewa pull request #473
Opened 2023-05-15 06:54 UTC by 23po

# Description

This feature makes it easier for a user to update details of a channel, they do not have to create a new channel everytime they want to introduce changes. 

- After a story is published the first time, the user does not have to save it again to update channel details.  
- Updates made  reflect on the db under channels/{{channelId}}.
- Fields not updated remain intact.

Fixes issue #453

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Video (optional)
[update channel details.webm](https://github.com/italanta/elewa/assets/48943229/cd83b3ba-367b-4e3b-a957-629c98538f35)

# How Has This Been Tested?

- [ ] Runs on Development server

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-15 06:55 UTC, 23po commented
@LemmyMwaura please review

2023-05-22 12:27 UTC, LemmyMwaura requested changes
This is still far from the required implementation. Check your console for more errors.

2023-05-22 12:27 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts
> + console.log(channel)
log statements ??

2023-05-22 12:27 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts
> + console.log(this.currentChannel)
also here

2023-05-22 12:27 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +import { CommunicationChannel } from '@app/model/convs-mgr/conversations/admin/system';
fix the order of imports

2023-05-29 11:57 UTC, closed without merging