💄 Assessment Feature UI #476
italanta/elewa pull request #477
Opened 2023-05-16 10:30 UTC by AnnaL001

# Description

This pull request entails an assessments view page containing a table of an organization's assessments with sorting and pagination capabilities. Aside from that, the assessment creation modal has been implemented to allow for the creation of assessments upon which one is redirected to the assessment edit page for adding configurations and questions. For the assessment edit page, sections for editing configurations and adding questions have been included. The remaining bits include the addition of form controls to a form array when an additional question is added, dynamic generation of the answer/option component when clicking the "+answer" button, alongside its form control, and the assessment view page UI containing the list of questions.

Fixes #476 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
**Assessment list page**
<img width="960" alt="assessments_page" src="https://github.com/italanta/elewa/assets/43697008/be536d39-2719-4e19-ab51-95cc4ea02068">

**Assessment edit page**
<img width="802" alt="assessment_edit" src="https://github.com/italanta/elewa/assets/43697008/a5f342f0-258a-42e3-bf44-68b6397a7a5d">

**Assessment creation modal**
<img width="962" alt="assessment_create_modal" src="https://github.com/italanta/elewa/assets/43697008/950d7241-fef0-4013-ba84-fb97aaa22a87">

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-05-18 08:15 UTC, LemmyMwaura requested changes
Really Amazing Work 🚀, Just some slight changes 

- We can have one page for viewing assessment (maybe view) and then two different components that we can toggle our form mode from (so if it's view mode we show the view component that just renders the data, if it's edit mode we just show the edit component) This will help us avoid redundancy where were fetching data from both components.

2023-05-18 08:15 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts
> +      questionForms: this._formBuilder.array([])
Let's save this as questionList -> easier to read

2023-05-18 08:15 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts
> +      answerForms: this._formBuilder.array([])
Also here as AnswersList or ChoicesList

2023-05-18 08:15 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment.service.ts
> +
Since this file interacts with our assessment store we can just have it in our Assessment state module.

2023-05-18 10:30 UTC, AnnaL001 commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts
> +      questionForms: this._formBuilder.array([])
Done

2023-05-18 10:30 UTC, AnnaL001 commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts
> +      answerForms: this._formBuilder.array([])
Done

2023-05-18 10:30 UTC, AnnaL001 commented on libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment.service.ts
> +
Done

2023-05-29 13:11 UTC, ReaganCn requested changes
Just a minor change

2023-05-29 13:11 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts
> +import { Observable } from 'rxjs';
Rxjs should come after angular

2023-05-30 05:53 UTC, AnnaL001 commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts
> +import { Observable } from 'rxjs';
Done

2023-06-07 08:54 UTC, LemmyMwaura approved these changes

2023-06-07 09:57 UTC, ReaganCn approved these changes
Good work

2023-06-07 11:02 UTC, merged