🎨 :Added dialog box for logins and validations.
italanta/elewa pull request #495
Opened 2023-05-18 19:31 UTC by Allan-Ngugi

# Description

 Issue #481 This pull request solves the issue of a user putting wrong credentials in the login section a dialog box has been put and displays the error in case of wrong credentials following validations set up in the form.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #481  Prompt user of failed login attempt

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Screenshot (optional)
![Screenshot from 2023-05-18 22-14-19](https://github.com/italanta/elewa/assets/105485948/945fdc08-bc6e-4a1a-9b20-e3776284ce74)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-22 12:12 UTC, LemmyMwaura approved these changes

2023-05-22 12:13 UTC, LemmyMwaura requested changes
A few changes still left

2023-05-22 12:13 UTC, LemmyMwaura commented on libs/features/app/auth/login/src/lib/components/login/login.component.html
> +      Incorrect password or email
Add translations for this.

2023-05-22 13:37 UTC, Allan-Ngugi commented
on it


On Mon, May 22, 2023 at 3:13 PM Lemmy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> A few changes still left
> ------------------------------
>
> In
> libs/features/app/auth/login/src/lib/components/login/login.component.html
> <https://github.com/italanta/elewa/pull/495#discussion_r1200430519>:
>
> > +        <input matInput formControlName="email" type="email" ***@***.***">
> +        <mat-error *ngIf="loginForm.get('email').errors?.required">Email is required</mat-error>
> +        <mat-error *ngIf="loginForm.get('email').errors?.email">Invalid email format</mat-error>
> +      </mat-form-field>
> +    </div>
> +
> +    <div [formGroup]="loginForm" fxLayout="row" fxLayoutAlign="start center">
> +      <mat-form-field id="password-input" class="special-input" fxFlex floatLabel="always">
> +        <mat-label class="form-label">{{ 'LOGIN.LOGIN-FORM.FLD-PASSWD' | transloco }}</mat-label>
> +        <input matInput formControlName="password" type="password" placeholder="************">
> +        <mat-error *ngIf="loginForm.get('password').errors?.required">Password is required</mat-error>
> +      </mat-form-field>
> +    </div>
> +
> +    <div *ngIf="loginFailed" class="login-failed-message">
> +      Incorrect password or email
>
> Add translations for this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa/pull/495#pullrequestreview-1436496644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEZM7EUGX7MJFKJGVZHKXTXHNJ6JANCNFSM6AAAAAAYG3XWGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-29 09:43 UTC, LemmyMwaura approved these changes

2023-05-29 09:44 UTC, merged