:art: (feat)Application Design on the Block base layout issue #13
italanta/elewa pull request #53
Opened 2022-09-02 08:04 UTC by trevin-livele

# Description

The issue requires the design of the block base layout to include an image,delete and copy options as well as block title 

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (#13 ) 
## Type of change

- [ ] New feature (non-breaking change which adds functionality)
# Demo

https://user-images.githubusercontent.com/60538411/188088027-d8ed9d2d-d2ad-46ef-a01c-d5684b6375a2.mp4

# Screenshot 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-05 10:00 UTC, jrosseel requested changes
Needs to be more dynamic and implement the correct variables

2022-09-12 05:34 UTC, ReaganCn requested changes
Good work. You need to correct the order of imports as shown in my comment

2022-09-12 05:34 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts
> +import { MultiLangModule } from '@ngfi/multi-lang';
Correct order of imports
>> Modules
>> Services
>> Components

2022-09-12 12:15 UTC, ReaganCn approved these changes

2022-09-12 14:43 UTC, merged