🎨 🔲 Add an upload button to video block modal #482
italanta/elewa pull request #537
Opened 2023-06-22 09:14 UTC by Calvin-Ngugi

# Description

This PR adds an upload button once a video has been loaded, so as to change the video. I have worked on this with Awadh @order6677

Fixes #482  

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

[demo4.webm](https://github.com/italanta/elewa/assets/26298045/a9b4a3bd-558e-4d09-92b7-0c12ee2f342a)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-06-26 09:38 UTC, LemmyMwaura requested changes
Good work, Just a small quick fix.

2023-06-26 09:38 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/modals/video-upload-modal/video-upload-modal.component.html
> +              <button type="button" (click)="openFileExplorer()" class="upload-button" *ngIf="videoPath">Upload</button>
Update the name to Update Video and add it to the translations

2023-06-26 14:02 UTC, Calvin-Ngugi commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/modals/video-upload-modal/video-upload-modal.component.html
> +              <button type="button" (click)="openFileExplorer()" class="upload-button" *ngIf="videoPath">Upload</button>
I have made the changes requested

2023-06-27 08:25 UTC, LemmyMwaura approved these changes

2023-06-27 08:26 UTC, merged