:wrench: Implement flowchart connectors
italanta/elewa pull request #54
Opened 2022-09-02 11:24 UTC by OGENDI

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-02 12:17 UTC, pmutua commented
@Derick Ogendi great! you've make a PR please edit it this is only the PR template it doesn't have information about what you did and what issue this is related to also do you have a screen shot showing that your implementation works?

2022-09-02 12:45 UTC, pmutua requested changes

2022-09-02 12:45 UTC, pmutua commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts
> +        type: FlowchartConnector.type,
@OGENDI leave this as it was the connector type should be of type `BezierConnector.type`.

2022-09-05 09:55 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts
> +        type: FlowchartConnector.type,
@pmutua , it is actually correct. The Flowchart should be used.

@OGENDI , which issue number is this PR for please?

2022-09-14 12:28 UTC, jrosseel commented
Closed due to inactivity

2022-09-14 12:28 UTC, closed without merging