:bug: :mag: When I search for an item I should only see relevant results fix #466
italanta/elewa pull request #545
Opened 2023-06-28 13:29 UTC by Beulah-Matt

# Description
Before, when a user searched for a block, the block was filtered but the headings of other blocks were also showing below the relevant result. 
For this fix, I am suggesting that for a filter to fully match, both the heading and block texts have to match, thus returning only the relevant results for both the category and blocks under it.

Fixes #466 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Screenshot (optional
[Screencast from 28-06-23 16:18:58.webm](https://github.com/italanta/elewa/assets/109944021/01ea5ce1-5bf3-4c62-bb4a-bff27070aefb)
)

# How Has This Been Tested?
Only relevant results show on search.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2023-06-29 12:30 UTC, LemmyMwaura requested changes
Good Attempt so far but this solution will lead to performance issues as Ngif will constantly keep calling the hasMatchingBlocks method every second as it keeps track of the value before deciding whether to show an item. 

To achieve our desired output we'll need to do all the filtering in the ts file and store the value/values in a variable or list that will allow us to decide whether to render that item.

2023-06-29 12:30 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +
No need for this as you can just check whether the filtered Block Property above is of length > 0

2023-06-29 12:30 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +
I don't think this variable is necessary

2023-07-03 07:31 UTC, Beulah-Matt commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +
@LemmyMwaura I am working on this. I'll let you know once I am done.

2023-07-05 12:44 UTC, LemmyMwaura requested changes
This is a much better approach but we're still making a function call in out template to evaluate an ngIf condition. Challenge: Use a pipe to determine whether we should render the title, The pipe should only listen to changes when the user types on the search field (if you need any help implementing this reach out

2023-07-05 19:26 UTC, Beulah-Matt commented
@LemmyMwaura , I have made some changes, let me know if they are what you had in mind.

2023-07-06 08:19 UTC, LemmyMwaura approved these changes
Yeah, this is perfect Well done 👏 
Made a few changes just to optimise it and improve the structure.

2023-07-06 08:20 UTC, merged