:sparkles: :convenience_store: Learners tab state layer
italanta/elewa pull request #556
Opened 2023-07-19 12:23 UTC by LemmyMwaura

# Description

This PR creates the state layer for the upcoming enrolled learner's page feature.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas

2023-07-21 07:29 UTC, ReaganCn approved these changes

2023-07-21 07:29 UTC, ReaganCn commented on libs/state/convs-mgr/learners/src/lib/services/learners.service.ts
> +}
You can add more methods to handle the enrolled learners. e.g. add learner, remove learner,  update learner,

2023-07-21 07:40 UTC, ReaganCn requested changes
Some functionalities missing

2023-07-21 07:52 UTC, ReaganCn requested changes

2023-07-21 07:52 UTC, ReaganCn commented on libs/features/convs-mgr/analytics/src/lib/analytics.router.module.ts
>    },
You can also add the route to reports section

2023-07-28 12:57 UTC, ReaganCn requested changes

2023-07-28 12:57 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts
> +                user.currentCourse = eventStack[0].name;
This can be done in a separate store that is responsible for the combining the two collections

2023-07-28 12:57 UTC, ReaganCn commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +    await enrolledUserService.getOrCreateEnrolledUser(this.endUser, 'whatsappUserId');
Creating of the enrolled end user should be batched and resolved later

2023-07-28 12:57 UTC, ReaganCn commented on libs/state/convs-mgr/learners/src/lib/services/learners.service.ts
> +    return this._enrolledLearners$$.get();
Getting enrolled users and end-users should be done here

2023-07-31 13:01 UTC, LemmyMwaura commented on libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts
> +    await enrolledUserService.getOrCreateEnrolledUser(this.endUser, 'whatsappUserId');
Done

2023-07-31 13:01 UTC, LemmyMwaura commented on libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/event-block.service.ts
> +		enrolledUserService: EnrolledUserDataService,
Yeah, that makes sense. Sorted.

2023-07-31 13:50 UTC, ReaganCn approved these changes

2023-07-31 13:53 UTC, merged