📈 🚧 Metabase integration on the analytics page
italanta/elewa pull request #559
Opened 2023-07-20 10:01 UTC by ReaganCn

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-25 09:25 UTC, jrosseel requested changes

2023-07-25 09:25 UTC, jrosseel commented on libs/state/convs-mgr/analytics/src/lib/services/metabase.service.ts
> +	constructor(private _aFF: AngularFireFunctions,
Use double spaces not 4

2023-07-26 07:12 UTC, ReaganCn commented on libs/features/convs-mgr/analytics/src/lib/pages/analytics-page/analytics-page.component.ts
> +    this._mbService.getMetabaseLink().subscribe((res: string) => {
done

2023-07-28 07:34 UTC, jrosseel approved these changes
Approved but we have to look at user permissions i.e. which user has access to this page (can't be all of them)

2023-08-01 14:01 UTC, jrosseel approved these changes

2023-08-09 12:59 UTC, merged