:art: feat(Application design): Layout of the Application ref: #24
italanta/elewa pull request #56
Opened 2022-09-05 12:22 UTC by meshack34

# Description
Reference the issue related to this PR as shown [here](https://github.com/italanta/italanta-apps/issues/24).
### Summary
*Fixes #24* completely
When a user logs in, they are able to navigated to the application homepage (Dashboard). Here they can view an analysis of all their bots and all the bots they are building and go to their builder.

 **Dependencies Added**
- Added font awesome
`npm install --save-dev @fortawesome/fontawesome-free`

**From here one can :**

Interact with the sidenav at the left which contains my navigation.
Interact with the user component which contains my user menu.
Interact with the application pages which contain the various features of the application.
We have prepared a new design to improve the current UI as shown below:

# Video and Screenshot

https://user-images.githubusercontent.com/41685560/186847859-4731385d-2c99-4034-bc29-cf295f56efcd.mp4

#
![elewscreen](https://user-images.githubusercontent.com/41685560/186846697-ce300924-1ebe-452b-9ba5-ffa63010c8a0.png)

Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code

2022-09-12 11:53 UTC, ReaganCn commented
Hello Meshack, 
A few things to note:
- The logo is skewed. It should keep the original aspect ratio as shown below. This also inludes other elements in the side-nav
![image](https://user-images.githubusercontent.com/34684844/189645102-7a22591a-bde4-4baf-9185-51d7be90d5ee.png)

- If you are making the menu retractable, make sure that the rest of the page reacts the same(expands and contracts)

2022-09-12 11:53 UTC, ReaganCn requested changes

2022-09-12 11:53 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
> +  border-right: 7px solid #351393;
Use variables from _variables.scss for colors.

2022-09-12 11:53 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
> +  color:#351393;
Same here. Use scss variables

2022-09-12 17:46 UTC, meshack34 commented
Hi, I have made changes. Have a look

On Mon, Sep 12, 2022 at 2:53 PM Reagan Charana ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
> <https://github.com/italanta/elewa/pull/56#discussion_r968307011>:
>
> >    color: mat-color($accent, A200);
> -  max-width: 25px;
> -  border-radius: 5px;
> +  padding-top:35px;
> +}
> +.category-children{
> +  background-color:#E0C4EC;
> +  border-right: 7px solid #351393;
>
> Use variables from _variables.scss for colors.
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
> <https://github.com/italanta/elewa/pull/56#discussion_r968307345>:
>
> > @@ -110,5 +141,21 @@ mat-nav-list {
>
>  .hov:hover, .child-header:hover {
>    cursor: pointer;
> -  background-color: mat-color($accent, A200);
> +  //background-color: mat-color($accent, A200);
> +
> +
> +
> +}
> +
> +.fa-gauge-high{
> +  color:#351393;
>
> Same here. Use scss variables
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa/pull/56#pullrequestreview-1103936777>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ6BEOBY6PEP3N4OVKED4MDV54KUZANCNFSM6AAAAAAQE6BAV4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-13 10:21 UTC, ReaganCn commented
You have just created the variable within the scss file and assigned it. We have a dedicated _variables.scss file that has the theme colors and you should use the variables from that file. It is located in libs/elements/theming/_variables.scss
Example:
`color: var(-- --convs-mgr-color-primary-yellow)`

2022-10-24 07:44 UTC, ReaganCn commented
Issue resolved by Faiso on PR #99

2022-10-24 07:44 UTC, closed without merging