⚡ 🫂 Improvements on multi tenant state layer
italanta/elewa pull request #560
Opened 2023-07-26 06:51 UTC by ReaganCn

# Description

This PR improves the multi-tenant state layer:
- Adding methods to get users of an organisation and orgs the users belong to
- Adding the permissions state layer and assignment handler
- Move the multi-tenant implementation to private folder

2023-07-28 07:33 UTC, jrosseel requested changes
Still somne work here

2023-07-28 07:33 UTC, jrosseel commented on libs/private/functions/organisation/src/lib/organisation-assign-user.handler.ts
> +export class OrganisationAssignUserHandler extends FunctionHandler<Organisation, boolean>
Please comment this whole file.
Consider moving the large json in _defaultPermissions into a seperate file default-permissions.json or .ts

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/private-organisation-state.module.ts
> +export class PrivateOrgStateModule
Comment

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/private-organisation-state.module.ts
> +export class PrivateOrgStateModule
Call MtOrgStateModule

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/services/organisation.service.ts
> +  createOrg(org: Organisation) {
This ideally is done on the backend.
Next sprint please fix this

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/services/organisation.service.ts
> +  createOrg(org: Organisation) {
https://firebase.google.com/docs/functions/auth-events

Use trigger:
functions.auth.user().onCreate((user)

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/services/organisation.service.ts
> +export class OrganisationService {
Comments comments comments

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/stores/organisation.store.ts
> +    this._sbS.sink = data$.subscribe(properties => {
Duplicate, will add an extra unnecessary listener

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/stores/organisation.store.ts
> +    return q;
Will get all users if user is null. Please make sure that we also have the correct backend security rules

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/stores/organisation.store.ts
> +  override update = (prop: Organisation) => super.update(prop);
Remove these two fns by overriding to noop.

override update = (prop: Organisation) => { return null; }

2023-07-28 07:33 UTC, jrosseel commented on libs/private/state/user/base/src/lib/services/clm-user.service.ts
> +    this._bs.httpsCallable('createNewUser')(user).subscribe();
return

2023-08-01 14:00 UTC, jrosseel requested changes

2023-08-01 14:00 UTC, jrosseel commented on libs/private/functions/organisation/src/lib/delete-user-from-organisation.handler.ts
> +        orgData.users.splice(orgData.users.indexOf(user.id), 1);
Splice will remove all users after the user no?

2023-08-01 14:00 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/services/organisation.service.ts
> +  constructor(private _router$$: Router,
Too many imports shows a code smell

2023-08-01 14:00 UTC, jrosseel commented on libs/private/state/organisation/main/src/lib/stores/permissions.store.ts
> +export class PermissionsStore extends Store<CLMPermissions>
Comments?

2023-08-03 08:35 UTC, ReaganCn commented on libs/private/functions/organisation/src/lib/delete-user-from-organisation.handler.ts
> +        orgData.users.splice(orgData.users.indexOf(user.id), 1);
'1' has been passed so it will only delete one item starting from the current index, which will only be the current index

2023-08-03 09:14 UTC, ReaganCn commented on libs/private/functions/organisation/src/lib/delete-user-from-organisation.handler.ts
> +        await orgsRepo.delete(orgData.id);
Okay...makes sense, but can the user be deleted from the db or should they have 'deleted: true'

2023-08-08 12:19 UTC, jrosseel approved these changes
Good to go pending some files which need clarifying comments

2023-08-09 07:03 UTC, merged