🎥 ❌ CLM-76 Enforce Whatsapp Media Limit
italanta/elewa pull request #565
Opened 2023-08-01 12:38 UTC by LemmyMwaura

# Description.
Enforce Whatsapp media limit on all media blocks before upload.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas

2023-08-11 10:24 UTC, ReaganCn requested changes
Just some minor changes

2023-08-11 10:24 UTC, ReaganCn commented on apps/conv-learning-manager/src/assets/i18n/en.json
> +          "MESSAGE-ONE": "Audio cannot be sent to whatsapp,",
You can group whatsapp messages together through a property "WHATSAPP", to be able to accomodate other platform requirements later

2023-08-11 10:24 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.html
> +        <div class="error-message" *ngIf="byPassedLimits.length">
This should be an array. For now there should also be one item in the array

2023-08-11 10:24 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.ts
> +import { SubSink } from 'subsink';
subsink before rxjs

2023-08-11 10:24 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.ts
> +      //Step 3 Check if file bypasses size limit.
Comment is wrongly placed

2023-08-11 10:30 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.html
> +        <div class="error-message" *ngIf="byPassedLimits.length">
It's an array.

2023-08-11 11:14 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.ts
> +      //Step 3 Check if file bypasses size limit.
Moved

2023-08-11 11:16 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.ts
> +import { SubSink } from 'subsink';
?? any reason why. They are both third-party modules.

2023-08-15 11:19 UTC, ReaganCn approved these changes

2023-08-15 11:19 UTC, merged