:sparkles:  CLM-96 Creating Single Learner Page
italanta/elewa pull request #570
Opened 2023-08-09 13:42 UTC by paulkahura

# Description

Added a student profile information page that shows the user's profile details, enrolled courses and their progress, and also their assessment history.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)
![image](https://github.com/italanta/elewa/assets/35740939/68f3b29f-8839-4a9b-a4ca-d3598e6e9b07)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-08-11 10:08 UTC, ReaganCn requested changes
Good first attempt. But still a lot of work to do.

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/components/learner-information/learner-information.component.ts
> +      EnrolledEndUserStatus[status].charAt(0).toUpperCase() +
Here you also dont need to pass the status through the method. Just access it from the current Learner property direct. 'this.currentLearner.status'.

Also no need to access char at. It's best practice to use enums. Just `if this.currentLearner.status === EnrolledUserStatus.Active return 'Active' else return 'inactive'`

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.html
>            <th class="table-header" mat-header-cell *matHeaderCellDef mat-sort-header="name">Name</th>
Use multi-lang

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/single-learner-page/single-learner-page.component.html
> +                <li><a routerLink="/learners/" routerLinkActive="router-link-active">Learners</a></li>
Multi-lang

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/single-learner-page/single-learner-page.component.ts
> +import { switchMap } from 'rxjs';
Check order of imports...Should be -  core angular imports, subsink, rxjs, domain imports and finally local imports

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/single-learner-page/single-learner-page.component.ts
> +  currentLearner!: EnrolledEndUser;
Class property declaration and definition in a class should happen before the constructor

2023-08-11 10:08 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/pages/single-learner-page/single-learner-page.component.ts
> +        console.log(this.currentLearner)
Remove console.log, after development

2023-08-11 11:20 UTC, paulkahura commented on libs/features/convs-mgr/learners/src/lib/components/learner-assessment-history/learner-assessment-history.component.ts
> +const ASSESSMENT_DATA: AssessmentResult[] = [
Was advised by lemmy to use the fake data since we could not get the data atm.

2023-08-16 06:21 UTC, ReaganCn requested changes
Good job! Just one minor change

2023-08-16 06:21 UTC, ReaganCn commented on libs/model/convs-mgr/learners/src/lib/enrolled-learners.interface.ts
>  import { IObject } from "@iote/bricks";
Order of imports. @iote before @app

2023-08-16 07:07 UTC, ReaganCn approved these changes

2023-08-16 07:22 UTC, merged