CLM-73-Saving-a-story-takes-too-long
italanta/elewa pull request #587
Opened 2023-08-30 09:45 UTC by JAPHETHNYARANGA

# Description

A new backend cloud function was created to help increase story saving speed. State mutations are still being done in the front-end though.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Stories are still able to be saved since this feature helps move saving story functionality to the backend.

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-31 06:51 UTC, ReaganCn requested changes
Good work. Check on the requested changes

2023-08-31 06:51 UTC, ReaganCn commented on apps/conv-lm-backend/src/app/story/create-Story.function.ts
> +
Add comment on what the function does

2023-08-31 06:51 UTC, ReaganCn commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +    .pipe(take(2))
Why take(2)?

2023-08-31 06:51 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/save-story.handler.ts
> +
Comment/Document this handler

2023-08-31 06:51 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/save-story.handler.ts
> +
Refer to how the other handlers have been documented

2023-08-31 06:51 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/save-story.handler.ts
> +  private async storySaved(data: StoryEditorState): Promise<{ success: boolean }> {
rename to saveStory. 'Story Saved' would have been okay if it only does something after the story has been saved

2023-08-31 06:51 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/services/block.service.ts
> +import * as admin from 'firebase-admin';
There is already a block data service in the bot engine. So this is a redundancy

2023-08-31 08:27 UTC, JAPHETHNYARANGA commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/services/block.service.ts
> +import * as admin from 'firebase-admin';
I discussed  this with Lemmy and discovered  that The existing block data service requires the channel to be passed in when initialising the class.

2023-08-31 12:26 UTC, ReaganCn requested changes

2023-08-31 12:26 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/create-story/src/lib/services/block.service.ts
> +import * as admin from 'firebase-admin';
Then instead of creating a new data service that just saves the block. You can extend the **BotDataService** and call the class something like "SaveBlockService".

2023-09-01 05:16 UTC, ReaganCn approved these changes

2023-09-01 06:17 UTC, merged