:sparkles:  CLM-136 Backend function to validate the story and return errors
italanta/elewa pull request #594
Opened 2023-09-06 08:25 UTC by paulkahura

# Description

Backend function to check story for  errors

#CLM-136 Check story for errors

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-07 07:50 UTC, ReaganCn requested changes
Good work. Some minor logic optimization required

2023-09-07 07:50 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/functions-convs-mgr-story-editor--check-story-for-errors.ts
> +export function functionsConvsMgrStoryEditorCheckStoryForErrors(): string {
Delete unused file

2023-09-07 07:50 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +        const listBlock = block as ListMessageBlock;
Use block.type to check if its a list block or questionblock or any other block with options

2023-09-07 07:50 UTC, ReaganCn commented on libs/model/convs-mgr/stories/main/src/lib/story-error.interface.ts
> +export enum FlowErrorType {
Also document this

2023-09-07 07:50 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +        if (!block.message || block.message.trim() == '') {
Move this check to a reusable function, and use the functions in all the places you are checking for this

2023-09-07 07:50 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +      connectionIds.add(connection.targetId);
Use sourceId as you will miss some unconnected blocks e.g. the last block that should be connected to the end block or options which are left hanging. In additin you will also need check if the first block is connected as its source id will be  the story id.

2023-09-11 06:12 UTC, ReaganCn requested changes

2023-09-11 06:12 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +              if (this.isMessageEmpty(option.message) && block.type !=34) {
Also this hardcoding

2023-09-11 06:12 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +export class FindStoryErrorHandler extends FunctionHandler<any, StoryError[]> {
Define orgId and story id as the request data type

2023-09-11 06:12 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +  private blockHasOptions(block: StoryBlock): block is ListMessageBlock | QuestionMessageBlock {
Also this function can be moved to the story block type file and use a switch statement like the rest of the block 'groups' there

2023-09-12 09:15 UTC, paulkahura commented
Not sure if I should remove the create-story from the angular json file

2023-09-12 09:17 UTC, ReaganCn requested changes
Great progress. Now update the code for reusability. See my comments

2023-09-12 09:17 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +            if( isInputOptionBlock(block.type) && this.isMessageEmpty(option.message)){
Any block that has options will always have 'options.message' so no need for isInputOptionBlock function

2023-09-12 09:17 UTC, ReaganCn commented on libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts
> +export function isInputOptionBlock(blockType: StoryBlockTypes) {
No need for this function. See comment above

2023-09-12 09:17 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +            if (!connectionIds.has(`i-${(index)}-${block.id}`)){
`!connectionIds.has(sourceId)` is being repeated a lot, so that means it can be moved to a reusable method 
```
isConnectionMissing(sourceId, blockId, optionId?: string)
````

The same goes with the EmptyTextField method
The method should therefore directly push the errors to the array. The errors should also be declared as a private property in the class so that it can be accessed by 'this' keyword.

**Note:** This is Pseodocode. So please use the appropriate syntax

2023-09-12 11:50 UTC, paulkahura commented on libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss
> +  min-height: 20000px!important;
the editor becomes small without it and one cannot scroll

2023-09-13 09:52 UTC, ReaganCn requested changes
Just some minor tweaks

2023-09-13 09:52 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +      this.checkEmptyTextField(block.message, block.id);
This shouldn't be here, as from the name of the function...retrieveBlocks is only suppossed to get blocks

2023-09-13 09:52 UTC, ReaganCn commented on libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
> +      if (isOptionBlock(block.type)) {
Also this. You can create a separate function called: findErrors that gets all the errors. Blocks and connections are then passed to it

2023-09-15 06:31 UTC, ReaganCn approved these changes
Good work. You can see that the code is much cleaner that the original one

2023-09-15 07:37 UTC, merged