🔧 CLM-64 A Link That Navigates User From Chats To Profile
italanta/elewa pull request #610
Opened 2023-09-20 21:04 UTC by JAPHETHNYARANGA

# Description

The user is able to jump to other related pages. In this case we created hyperlink on the name so that it opens up the learner's profile page on click.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-21 07:05 UTC, ReaganCn requested changes
Still some work. Make changes as discussed

2023-09-28 05:50 UTC, ReaganCn requested changes

2023-09-28 05:50 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +            if (learner.id !== undefined) {
Please fix all instances of this

2023-09-28 05:50 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +              this.extractedLearnerId = learner.id.toString()
And this

2023-09-29 05:44 UTC, ReaganCn approved these changes
Good progress

2023-10-19 06:40 UTC, LemmyMwaura requested changes

2023-10-19 06:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +  resetChatNameColor() {
one of these variables is redundant. use one

2023-10-19 06:40 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +  extractedLearnerId: string;// This variable will be used to store the ID of a learner extracted from enrolled learners.
This name is self-descriptive. No need for comment

2023-10-23 06:10 UTC, LemmyMwaura commented
Closing this for now

2023-10-23 06:10 UTC, closed without merging