:art: {feat }User menu #8
italanta/elewa pull request #62
Opened 2022-09-13 22:04 UTC by trevin-livele

# Description

The changes in the issue #8  regards the user menu.I have updated the ui and made it meet the design needs and also separated the logout functionality to a separate component.

Fixes # (issue #8 ) 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Screenshot 
![usermenu](https://user-images.githubusercontent.com/60538411/190017420-e386eaee-37c4-4d05-a473-5ab6e508941e.png)

# demo

https://user-images.githubusercontent.com/60538411/190017317-4cd20591-ddeb-4b53-b301-5f96ce84c1a9.mp4

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-14 06:22 UTC, ReaganCn reviewed
Please have a look at the code changes requested. In regards to the User menu component, you can fit only at the top menu bar, because now it's between the top menu bar and the breadcrumb.

Otherwise, keep it up!

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/app-logout/app-logout.component.html
> +<button mat-menu-item (click)="logout()">Log out</button>
Use multi-language

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.html
>      <button mat-menu-item>My profile</button>
Use multilanguage

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.html
> +      Admin&nbsp;
Use multi-language

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss
> +  background-color: #fafafa;
Implement using scss variables for all colors. Variables to use are in libs/elements/theming/_variables.scss
Example:
`background-color: var(--variable-name)`

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss
> +color: #8F8F8F;
Same here. Use scss variables

2022-09-14 06:22 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss
> +  background-color: white;
Use scss variables. See next comment

2022-09-14 06:23 UTC, ReaganCn requested changes
Please have a look at the code changes requested. In regards to the User menu component, you can fit only at the top menu bar, because now it's between the top menu bar and the breadcrumb.

Otherwise, keep it up!

2022-09-14 10:52 UTC, trevin-livele commented
hello sir @ReaganCn i have made the changes

2022-09-15 06:43 UTC, ReaganCn approved these changes
Good work Trevin! 💪

2022-09-15 08:24 UTC, trevin-livele commented
> Good work Trevin! muscle

:+1: thank you sir

2022-09-27 07:34 UTC, trevin-livele commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.html
> +      Admin&nbsp;
hello sir @jrosseel  I have changed the roles area sir its now dynamic.For the arrow_drop_down it comes from mat icons  i have to call it that way {arrow_drop_down }  if i remove it the drop down icon disappears.

2022-10-24 07:36 UTC, ReaganCn requested changes
Good work. Check the below changes. We changed the way we implement icons

2022-10-24 07:36 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.ts
> +import { faCaretDown } from '@fortawesome/free-solid-svg-icons';
We are now using the cdn for implementing font awesome icons. See: https://github.com/italanta/elewa/pull/97

2022-10-24 07:36 UTC, ReaganCn commented on libs/elements/layout/user-menu/src/lib/user-menu.module.ts
> +    FontAwesomeModule
Remove Font Awesome Module import. See PR https://github.com/italanta/elewa/pull/97

2022-11-01 07:22 UTC, IanOdhiambo9 requested changes

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/app-logout/app-logout.component.ts
> +import { Observable } from 'rxjs';
Order of imports as below

import { Component } from '@angular/core';

import { Observable } from 'rxjs';

import { User } from '@iote/bricks';
import { UserService, AuthService} from '@ngfi/angular';

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/app-logout/app-logout.component.ts
> +  constructor(userService: UserService<User>, private _authService: AuthService) {}
move _authService below UserService

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.html
> +      <fa-icon id="dropdown-icon" [icon]="dropdownIcon"></fa-icon>
Use CDN icons with <i> tag

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.html
> -    <button mat-menu-item (click)="logout()">Log out</button>
Use multilang for this text

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss
> +#dropdown-icon {
use variable colors -> can be found in libs/elements/theming

eg. color: var(--convs-mgr-color-primary-yellow);

2022-11-01 07:22 UTC, IanOdhiambo9 commented on libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.ts
> +  constructor(userService: UserService<User>, private _router: Router) {
move UserService below router

2022-11-07 14:06 UTC, closed without merging