Delete block#14
italanta/elewa pull request #65
Opened 2022-09-15 08:50 UTC by CarolGitonga

# When a user clicks delete on the side menu of a block, the block needs to be deleted from the editor. Upon saving and reloading, the block needs to be removed

Fixes # (# 14) 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-15 10:02 UTC, pmutua requested changes

2022-09-15 10:02 UTC, pmutua commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
> +>>>>>>> main
@CarolGitonga you missed out on removing `>>>>>>> main` when you were resolving the conflicts. Remove this.

2022-09-15 11:26 UTC, CarolGitonga commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
> +>>>>>>> main
Okay

2022-09-15 11:50 UTC, CarolGitonga commented
@pmutua .I have removed the code

2022-09-16 06:59 UTC, ReaganCn requested changes
The block is not being deleted, based on your implementation. As the block needs to be removed upon saving/reloading.

You can record a short video to demonstrate this if it is working.

2022-09-16 06:59 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +    let confirmDelete = confirm('Are you sure you want to delete this block')
If there is a confirm dialog, would prefer to have a separate dialog component for this. So just remove the confirm for now

2022-09-16 08:57 UTC, CarolGitonga commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +    let confirmDelete = confirm('Are you sure you want to delete this block')
@ReaganCn Okay

2022-09-26 11:04 UTC, jrosseel commented
This implementation is missing a state interaction and thus not removing the block

2022-10-12 14:12 UTC, closed without merging