💄 ✨ (feat) Audio block interface. ref #27
italanta/elewa pull request #66
Opened 2022-09-15 09:18 UTC by Lucywambui

# Description
This PR closes part of issue #27. It implements the audio block interface.

## Type of change
UI and feature addition

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Uploading Screenshot 2022-09-15 at 12.17.19.png…]()

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2022-09-16 06:10 UTC, ReaganCn requested changes

2022-09-16 06:10 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.scss
> +    border: 1px solid black;
Use `--convs-mgr-color-text-black` for flexibility

2022-09-19 05:52 UTC, ReaganCn approved these changes
Good work!

2022-09-26 10:52 UTC, jrosseel commented
Closed as we await ImageBlock

2022-09-26 10:52 UTC, closed without merging