Name block redesign block redesign #624
italanta/elewa pull request #663
Opened 2023-10-01 13:58 UTC by Mutagah

# Description

1. Addition of the ellipsis icon and its functionality containing the 3 icon blocks.
2. name-block redesigning

Fixes #624

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot
![Screenshot from 2023-10-01 16-54-25](https://github.com/italanta/elewa/assets/106149210/aebb3bf3-a446-47a5-8079-373b290f119e)

![Screenshot from 2023-10-01 16-55-19](https://github.com/italanta/elewa/assets/106149210/6b3d087d-b833-4d19-a800-710d28536b92)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-11 13:21 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/name-message-block/src/lib/components/name-block/name-block.component.html
> -
We'll have to change the state layer to account for this, so for now just leave and then edit it to match the new design

2023-10-11 13:23 UTC, LemmyMwaura requested changes
Same changes as those i've requested in #662

2023-11-02 06:03 UTC, LemmyMwaura commented
Kindly Resolve your conflicts.

2023-11-02 09:01 UTC, Mutagah commented
> Kindly Resolve your conflicts and leave the anchor as left for now @Mutagah

Changes requested made.

2023-11-08 05:22 UTC, LemmyMwaura commented
Closing this as you've merged a lot of block design issues. So next step is to pick something a bit more challenging. I'll assign you an issue.

2023-11-08 05:22 UTC, closed without merging