Email block redisign #623
italanta/elewa pull request #664
Opened 2023-10-01 14:10 UTC by dennis-mburu

# Description
This PR redesigns the email block to enhance its usability and visual appeal

Fixes #623

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![email-menu-closed](https://github.com/italanta/elewa/assets/65117575/09b9e549-1cf1-4350-a5a1-59e39422c737)
![email-menu-open](https://github.com/italanta/elewa/assets/65117575/7a35af55-5a8d-4a05-8ca9-7cfc05e0bb45)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-10-11 13:38 UTC, LemmyMwaura reviewed
Good first attempt. Just some cosmetic changes

2023-10-11 13:38 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/email-message-block/src/lib/components/email-block/email-block.component.html
> -		<app-default-option-field [jsPlumb]="jsPlumb" [blockFormGroup]="emailMessageForm"></app-default-option-field>
We'll have to change the state layer to account for this, so for now just leave it and then edit the component to match the new design

2023-10-11 13:38 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts
> +
This will become redundant once we add the default option back

2023-10-11 13:50 UTC, LemmyMwaura requested changes
Changes above

2023-10-13 10:31 UTC, dennis-mburu commented
Closing this PR, kindly reference PR #709  which has all the latest updates

2023-10-13 10:31 UTC, closed without merging