Location input block redesign
italanta/elewa pull request #665
Opened 2023-10-01 19:46 UTC by darlene9497

# Description

This pull request addresses the redesign of the "Location Input Block" component as outlined in the provided designs. The goal of this PR is to enhance the usability and visual appeal of the component while adhering to the acceptance criteria,

Fixes #631 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-11 13:45 UTC, LemmyMwaura requested changes
Good first attempt. Just some cosmetic changes. Also same changes as those requested on your other PR

2023-10-11 13:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
> +                <img [src]="iconClass" class="icon-color"/>
Since this is a reusable block have a switch statement here to use the img tag for svgs and i tags for fontawesome icons. Check out how @Mutagah  has done it.

2023-10-12 07:48 UTC, darlene9497 commented
@LemmyMwaura I have made the requested changes

2023-11-02 06:04 UTC, LemmyMwaura commented
Kindly resolve your conflicts @darlene9497

2023-11-08 05:25 UTC, LemmyMwaura approved these changes

2023-11-08 05:26 UTC, LemmyMwaura approved these changes

2023-11-08 05:29 UTC, merged