:art: Question buttons block redesign
italanta/elewa pull request #676
Opened 2023-10-03 15:30 UTC by darlene9497

# Description

This PR addresses the redesign of the "Question buttons block", enhancing the usability and visual appeal of the component.

Fixes #622 

# Screenshot
![Screenshot from 2023-10-12 10-26-25](https://github.com/italanta/elewa/assets/117742892/4f68bba0-98b0-4148-add2-f562c25c16bd)
![Screenshot from 2023-10-11 21-15-38](https://github.com/italanta/elewa/assets/117742892/64a9f760-d6b0-4c2d-832f-b36bee80af5d)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-10-11 12:52 UTC, LemmyMwaura requested changes
Very good first attempt, just some cosmetic changes left and then we can merge this.

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.html
> +        type="text" [placeholder]="'Option ' + optionIndex" [maxlength]="charMaxlength" fxFlexFill>
Let's leave the placeholder as click here to edit.

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.ts
Let's lose the option index, don't mutate the message value when adding new option

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.ts
> +    this.optionIndex = +this.formGroupNameInput + 1;
Let's lose this.

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
> +                    </button>
Add this to translations (Edit, Copy and Delete) and then wrap them in span tags then add a spacing of 5px

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/questions-block.jsplumb.ts
> +    anchor: [0, 0.1, 0, 1],
Good

2023-10-11 12:52 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts
> +  }
Let's lose this method and anywhere it's called (It mutates the value of our form which is not ideal especially if the user has entered values and wants to save his/her content),

 just set a placeholder of `click here to edit` or `option`

2023-10-11 18:18 UTC, darlene9497 commented
@LemmyMwaura I have made the requested changes, kindly review and refer to the screenshots

2023-10-12 07:39 UTC, darlene9497 commented
@LemmyMwaura I have made the changes

2023-10-12 09:41 UTC, LemmyMwaura approved these changes

2023-10-12 09:49 UTC, merged