Event block redesign
italanta/elewa pull request #678
Opened 2023-10-06 05:20 UTC by darlene9497

# Description

This pull request addresses the redesign of the "Event Block" component as outlined in the provided designs. The goal of this PR is to enhance the usability and visual appeal of the component while adhering to the acceptance criteria,

Fixes #635

# Screenshot 
![Screenshot from 2023-10-06 08-15-52](https://github.com/italanta/elewa/assets/117742892/f1420ef8-837e-496c-a7b8-ca355e34e6b3)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-10-12 12:48 UTC, LemmyMwaura requested changes

2023-10-12 12:48 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/event-block.jsplumb.ts
>      maxConnections: -1
Use the default option but style it no need for the extra addEndpoint call

2023-10-13 10:00 UTC, darlene9497 commented
@LemmyMwaura I have made the requested changes

2023-11-02 06:05 UTC, LemmyMwaura commented
Kindly resolve your conflicts @darlene9497

2023-11-02 06:08 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/event-block.jsplumb.ts
> +    anchor: [0, 0.18, 0, 1]
leave the anchor as left for now and max connections should still be set to -1.

2023-11-08 05:15 UTC, LemmyMwaura approved these changes

2023-11-08 05:15 UTC, merged