Video input block redesign block redesign #644
italanta/elewa pull request #679
Opened 2023-10-06 21:26 UTC by Mutagah

# Description

This PR makes UI changes to the video input block.

Fixes #644

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-10-07 00-19-24](https://github.com/italanta/elewa/assets/106149210/76c7425c-1b6f-4101-a5a2-0f7fa1f03db7)

![Screenshot from 2023-10-07 00-20-16](https://github.com/italanta/elewa/assets/106149210/c38e51e1-33bc-4669-8631-0c187df2b4e1)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-10-12 12:50 UTC, LemmyMwaura requested changes
Same changes as the Phone Block

2023-11-02 06:07 UTC, LemmyMwaura reviewed
Kindly resolve your conflicts, also leave the Jsplumb anchor as left for now.

2023-11-02 12:54 UTC, Mutagah commented
> Kindly resolve your conflicts, also leave the Jsplumb anchor as left for now.

Requested change has been addressed.

2023-11-08 05:18 UTC, LemmyMwaura approved these changes

2023-11-08 05:18 UTC, merged