Image input block redesign block redesign #639
italanta/elewa pull request #682
Opened 2023-10-09 07:47 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-12 12:57 UTC, LemmyMwaura requested changes

2023-10-12 12:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
>              </div>
Sync the latest changes and then use the menu set in the codebase. But you can switch the icon to the one you have over hear

2023-10-12 12:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts
> +    icon: '/assets/icons/ph_image-light.svg',
Pull the latest changes. There's a switch between SVGs and i tags. We will deprecate the i tags after all blocks switch to svgs

2023-10-12 12:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-input-block.jsplumb.ts
>    });
No need for this. We've decided to just keep the original default option. So just-style that

2023-10-12 12:57 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.html
> +        <img *ngIf="block.message === 'Image Input'" [src]="block.blockIcon" />
Use the switch-case already in the codebase at the block component section.

2023-11-02 06:14 UTC, LemmyMwaura requested changes

2023-11-02 06:14 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +    { id: 'io-image-input-block' , type: StoryBlockTypes.ImageInput, message: 'Image Input', blockIcon:this.getBlockIcon(StoryBlockTypes.ImageInput), svgIcon:this.getSvgIcon(StoryBlockTypes.ImageInpu
leave this as blockIcon

2023-11-02 06:14 UTC, LemmyMwaura commented on libs/model/convs-mgr/stories/blocks/main/src/lib/story-block.interface.ts
> +  svgIcon?: string;
No need for this variable

2023-11-02 06:14 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.html
> +          <img src="{{ block.svgIcon }}" class="svgIcon">
just use the blockIcon over here

2023-11-02 06:14 UTC, LemmyMwaura commented
Kindly sync your changes and resolve the conflicts

2023-11-03 05:19 UTC, levy-web commented
@LemmyMwaura , I have merged with develop and done with requested changes

2023-11-03 12:42 UTC, LemmyMwaura requested changes
One final change.

2023-11-03 12:42 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/utils/transformers/image-input-block.jsplumb.ts
> +    anchor: [0, 0.2 , 0, 1],
Let's leave this as "Left" for now

2023-11-03 13:40 UTC, levy-web commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/utils/transformers/image-input-block.jsplumb.ts
> +    anchor: [0, 0.2 , 0, 1],
ok on it

2023-11-05 07:25 UTC, levy-web commented
@LemmyMwaura , done with requested changes

2023-11-08 05:16 UTC, LemmyMwaura approved these changes

2023-11-08 05:17 UTC, LemmyMwaura approved these changes

2023-11-08 05:17 UTC, merged