Document block redesign block redesign #640
italanta/elewa pull request #684
Opened 2023-10-09 14:40 UTC by Mutagah

# Description

This PR makes UI changes to document block redesign.

Fixes #640

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![Screenshot from 2023-10-09 17-12-10](https://github.com/italanta/elewa/assets/106149210/5e7f59cb-efa7-4c51-be99-f9e757eab920)

![Screenshot from 2023-10-09 17-13-17](https://github.com/italanta/elewa/assets/106149210/51c120d9-3594-495e-9e89-6356e6bbd1e3)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-12 12:58 UTC, LemmyMwaura requested changes
Same changes as those requested on the phone block

2023-11-02 06:19 UTC, LemmyMwaura requested changes
Almost done just sync your changes and resolve conflicts

2023-11-02 06:19 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +
should be `svgIcon!: string;` or `svgIcon: string;`

2023-11-02 06:19 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts
> +    anchor: [0, 0.11 , 0, 1],
lets leave this as left for now.

2023-11-02 08:32 UTC, Mutagah commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +
> should be `svgIcon!: string;` or `svgIcon: string;`

Changes requested have been made.

2023-11-02 08:33 UTC, Mutagah commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts
> +    anchor: [0, 0.11 , 0, 1],
> lets leave this as left for now.

Changes requested have been addressed.

2023-12-06 06:59 UTC, LemmyMwaura approved these changes

2023-12-06 06:59 UTC, merged