:sparkles:  :left_speech_bubble: CLM-48: Abiltiy to create business initiated messages
italanta/elewa pull request #686
Opened 2023-10-10 01:40 UTC by paulkahura

# Description

Message templates frontend.

CLM-48: Ability to create and register busines initiated messages

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-11 06:16 UTC, ReaganCn requested changes

2023-10-11 06:16 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-list/message-template-list.component.ts
> +    throw new Error('Method not implemented.');
I thought this is already implemented

2023-10-11 06:16 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-single-settings/message-template-single-settings.component.ts
> +  canBeScheduled = false;
Also no need to set it to false

2023-10-11 06:16 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-single-settings/message-template-single-settings.component.ts
> +        );
You can declutter the switch statement by moving the case functionalities to different methods

2023-10-11 06:16 UTC, ReaganCn commented on libs/private/state/message-templates/src/lib/service/message-template.service.ts
> +import { MessageTemplateStore } from '../store/message-template.store';
Order of imports

2023-10-11 06:16 UTC, ReaganCn commented on libs/private/state/message-templates/src/lib/store/message-template.store.ts
> +import { of } from 'rxjs';
Order of imports

2023-10-12 10:03 UTC, paulkahura commented on libs/model/convs-mgr/functions/src/lib/base/message-template.interface.ts
> +  header?: TemplateHeader | TextHeader;
here I get an error of tex not existing on header

2023-10-12 12:36 UTC, ReaganCn approved these changes

2023-12-19 14:03 UTC, LemmyMwaura commented
CLosing as this was merged internally

2023-12-19 14:03 UTC, closed without merging