Assessment block redesign block redesign #645
italanta/elewa pull request #688
Opened 2023-10-10 10:14 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-13 08:49 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts
> +    const inputs = document.getElementsByClassName('option');
Any reason for this switch?

2023-10-13 08:49 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
>                  <h4 class="block-title"> {{ blockTitle | transloco }}</h4>
Sync the latest changes there's a cleaner way to do this

2023-10-13 08:50 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
>              </div>
Sync your branch to get the latest changes

2023-10-13 08:51 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.html
> +        <img *ngIf="block.message === 'Assessment'" [src]="block.blockIcon" />
Use ngIf else with the else section in an ngtemplate to showcase this. (sync changes)

2023-10-15 08:38 UTC, levy-web commented on libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts
> +    const inputs = document.getElementsByClassName('option');
I added the option class with a maximum width so as to display the connectors at the end. when I use input-score-max connectors are at the center

2023-11-02 06:35 UTC, LemmyMwaura requested changes
Sync your changes and resolve conflicts

2023-11-02 06:35 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/assessment-brick.jsplumb.ts
> +    anchor: [0, 0.16 , 0, 1],
Just have this as left for now.

2023-11-02 06:35 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +    { id: 'assessment-brick', type:StoryBlockTypes.Assessment, message: 'Assessment', svgIcon:this.getSvgIcon(StoryBlockTypes.Assessment), blockIcon:this.getBlockIcon(StoryBlockTypes.Assessment),  bl
Use the blockIcon property so no need to change this.

2023-11-03 12:55 UTC, LemmyMwaura approved these changes

2023-11-03 12:58 UTC, merged