:fire::tada:first commit with 70% work done
italanta/elewa pull request #691
Opened 2023-10-10 20:36 UTC by kiplangat01

# Description

This PR fixes issue #638 Sticker Block Redesign

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #638 

# Screenshot 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-13 09:10 UTC, LemmyMwaura requested changes
Sync the latest changes then request review

2023-10-13 09:10 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/sticker-block.jsplumb.ts
>    });
remove the extra endpoint and then return the default option.

2023-10-31 14:19 UTC, LemmyMwaura requested changes

2023-10-31 14:19 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
>  import { FileStorageService } from '@app/state/file';
icon is selected from the parent block component

2023-10-31 14:19 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
> +  }
icon is selected from parent

2023-10-31 14:19 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
> +
same here. should be accessed from the parent block component

2023-11-01 05:52 UTC, kiplangat01 commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
>  import { FileStorageService } from '@app/state/file';
this is to handle the icon in the middle of block where you click to upload file

2023-11-01 05:52 UTC, kiplangat01 commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
> +
this is to handle the icon in the middle of block where you click to upload file

2023-11-03 13:15 UTC, LemmyMwaura requested changes

2023-11-03 13:15 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
> +
ah, okay that makes sense. leave it as is.

2023-11-03 13:15 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
>  import { FileStorageService } from '@app/state/file';
Okay, nevermind. Leave it as is.

2023-11-14 06:26 UTC, LemmyMwaura commented
![sticker](https://github.com/italanta/elewa/assets/20738858/c03d9c77-e32b-4408-ba90-eaaad929c572)

The design is off and the icon is not centered

2023-11-16 06:52 UTC, LemmyMwaura approved these changes

2023-11-16 06:53 UTC, merged