CLM-634 Keyword jump block redesign block redesign
italanta/elewa pull request #692
Opened 2023-10-10 20:56 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-13 09:34 UTC, LemmyMwaura requested changes
Sync the latest changes.

2023-11-02 06:58 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
> -      </div>
Any reason this has been omitted?

2023-11-02 06:58 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
> -    </button>
Any reason this has been removed?

2023-11-02 06:58 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/keyword-jump-block.jsplumb.ts
> +    anchor: [0, 0.3 , 0, 1],
Just leave this as left

2023-11-03 04:02 UTC, levy-web commented on libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
> -    </button>
its removed from required design

2023-11-03 04:03 UTC, levy-web commented on libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
> -      </div>
so as to align with required design

2023-11-03 04:19 UTC, levy-web commented
@LemmyMwaura i have merged with develop and fixed required changes, kindly review.

2023-11-03 13:30 UTC, LemmyMwaura approved these changes

2023-11-03 13:31 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
> -    </button>
mmh, okay. we'll go with this.

2023-11-03 13:33 UTC, merged