Location input block
italanta/elewa pull request #698
Opened 2023-10-11 17:16 UTC by Dancunrandy

# Description

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-13 09:39 UTC, LemmyMwaura commented
Update the PR description and add a screenshot

2023-10-13 12:29 UTC, Dancunrandy commented
@LemmyMwaura have added the screenshot

2023-11-02 07:22 UTC, LemmyMwaura requested changes
Kindly Sync your changes and resolve conflicts

2023-11-02 07:22 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/location-block.jsplumb.ts
>    });
Remove the extra jsplumb endpoint, return the default option for now.

2023-11-02 10:07 UTC, Dancunrandy commented
@LemmyMwaura resolved the conflicts and  enabled default option, take a look.

2023-11-05 10:10 UTC, closed without merging