new svg icons
italanta/elewa pull request #707
Opened 2023-10-12 16:59 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-02 07:31 UTC, LemmyMwaura requested changes
Good job just simplify the filter pipe and resolve conflicts

2023-11-02 07:31 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/webhook-block/src/lib/pipes/filter.pipe.ts
> +  }
Good job 👍 but simplify this. No need to create the extra list when we can just return a filtered list of value (rename to variables).

2023-11-02 07:31 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/webhook-block.jsplumb.ts
>      maxConnections: -1
let's leave this as 'Left' for now

2023-11-03 06:34 UTC, levy-web commented
@LemmyMwaura , I have merged with develop and done with requested changes.

2023-11-03 13:21 UTC, LemmyMwaura commented
@levy-web resolve conflicts

2023-11-04 03:40 UTC, levy-web commented
@LemmyMwaura I hve resolved the conflicts

2023-11-16 06:55 UTC, LemmyMwaura requested changes

2023-11-16 06:55 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/webhook-block/src/lib/components/webhook-block/webhook-block.component.ts
> +    })
The webhook form already exists, you are supposed to modify its values not create a new one

2023-11-17 06:43 UTC, LemmyMwaura requested changes

2023-11-17 06:43 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/webhook-block/src/lib/components/webhook-block/webhook-block.component.ts
> +    }
don't add any formControls. get the existing ones and mutate their values with what the user adds.

2023-12-08 11:56 UTC, merged