Email redesign #623
italanta/elewa pull request #709
Opened 2023-10-13 10:25 UTC by dennis-mburu

# Description
This PR redesigns the email block to enhance its usability and visual appeal

Fixes #623

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![email-menu-open](https://github.com/italanta/elewa/assets/65117575/d743cc8c-07f8-400c-9863-11408eefdbc3)
![email-redesign-updated](https://github.com/italanta/elewa/assets/65117575/5fc977c0-3e73-43d0-851c-04b6d2f4e3c7)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-11-02 07:34 UTC, LemmyMwaura requested changes
Kindly sync and resolve conflicts

2023-11-02 07:34 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts
> +    anchor: [0 ,0.23, 0, 1],
Let's leave this as Left for now

2023-11-03 10:56 UTC, dennis-mburu commented
I have updated accordingly. Kindly review @LemmyMwaura

2023-11-14 06:10 UTC, LemmyMwaura approved these changes
Add the new icon to the

2023-11-14 06:10 UTC, merged