Video block redesign #643
italanta/elewa pull request #711
Opened 2023-10-13 12:23 UTC by dennis-mburu

# Description
This PR redesigns the video block to enhance its usability and visual appeal

Fixes #643 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![video-block](https://github.com/italanta/elewa/assets/65117575/744ec671-d3fb-4616-87f7-5ee18b972172)
![video-menu](https://github.com/italanta/elewa/assets/65117575/f1670ca1-5659-42db-8f24-6e8831c20bdd)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-10-25 07:29 UTC, LemmyMwaura requested changes

2023-10-25 07:29 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.html
> +          <img src="assets/svgs/blocks/system-uicons_video.svg" alt="">
use ngIf over here to switch between icons. Check out how it's been done on other blocks

2023-10-26 08:14 UTC, dennis-mburu commented
I've updated accordingly, kindly review @LemmyMwaura

2023-11-02 07:54 UTC, LemmyMwaura requested changes
Kindly sync and resolve conflicts, then ping me.

2023-11-02 07:54 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts
> +    anchor: [0, 0.13, 0, 1],
leave this as 'Left'

2023-11-02 07:54 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
> +import { iconsAndTitles } from '../../../../../main/src/lib/model/icons-and-titles';
Try importing this from its aliased path.

2023-11-03 12:08 UTC, dennis-mburu commented
Made all the required changes. Kindly review @LemmyMwaura

2023-11-16 06:56 UTC, LemmyMwaura approved these changes

2023-11-16 06:57 UTC, merged