Conditional block redesign
italanta/elewa pull request #712
Opened 2023-10-13 13:07 UTC by Dancunrandy

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-26 19:40 UTC, Dancunrandy commented
@LemmyMwaura , resolved the checkbox, it's now clickable

2023-11-02 08:00 UTC, LemmyMwaura requested changes

2023-11-02 08:00 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/conditional-block.jsplumb.ts
> +    anchor: [0,0.17,0,1],
Leave this as 'Left' for now

2023-11-02 08:00 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/conditional-block.jsplumb.ts
> +
remove this, 'the second endpoint'

2023-11-02 08:00 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.html
> -
return the default option for now. (we'll remove it later)

2023-11-02 08:01 UTC, LemmyMwaura commented
Also, kindly resolve your conflicts

2023-11-05 09:24 UTC, Dancunrandy commented
@LemmyMwaura resolved the conflicts, activated default and restored previous dot position

2023-11-16 06:59 UTC, LemmyMwaura requested changes

2023-11-16 08:06 UTC, Dancunrandy commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/utils/transformers/conditional-block.jsplumb.ts
> +  // });
@have done the synching and removed completely the above part as requested.

2023-11-16 09:41 UTC, LemmyMwaura requested changes
Just noticed the add option is not properly styled. Can you take care of this please? Also, the select option should be disabled when the custom variable checkbox is selected.

<img width="331" alt="Screenshot 2023-11-16 at 12 39 02" src="https://github.com/italanta/elewa/assets/20738858/92d7b071-0ec9-411a-a899-fb9390c5980e">

2023-11-16 19:57 UTC, Dancunrandy commented
@LemmyMwaura  styled the add option properly and the select option is disabled when the custom variable checkbox is selected.

2023-11-21 14:45 UTC, LemmyMwaura requested changes
If not kindly rename but everything else looks good to me.

2023-11-21 14:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.ts
> +  constructor(private fb: FormBuilder, private variables: VariablesService) {
Is there any reason this was changed from _fb to fb or _sBs to subsink ??

2023-11-21 14:53 UTC, Dancunrandy commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.ts
> +  constructor(private fb: FormBuilder, private variables: VariablesService) {
No, there wasn't, i think my vs code  did auto correction while fixing the errors, i can restore the original code if you like.

2023-11-21 14:55 UTC, Dancunrandy commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.ts
> +  constructor(private fb: FormBuilder, private variables: VariablesService) {
ok, i will

2023-11-21 15:11 UTC, Dancunrandy commented
@LemmyMwaura ,have renamed the code

2023-12-01 09:43 UTC, LemmyMwaura commented
Kindly sync the latest changes, the design is the only missing thing. I refactored the design for the question, list and event blocks etc. You can just copy the design? including the options which are still in the old design format. @Dancunrandy

2023-12-06 07:38 UTC, LemmyMwaura approved these changes

2023-12-06 07:38 UTC, merged