🎨 Jump Block Redesign: block redesign (#627)
italanta/elewa pull request #713
Opened 2023-10-13 13:12 UTC by randy-kip

# Description

The "Jump Block" component in the app is redesigned to enhance its usability and visual appeal.

Fixes #627

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality.

# Screenshot
![Screenshot (138)](https://github.com/italanta/elewa/assets/84719074/18b70a82-3ea9-4f04-85f1-57b3be7781c8)

# How Has This Been Tested?

Visual test, comparison to the image in the issue. The result can also be compared to the Figma sample.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-11-02 08:02 UTC, LemmyMwaura requested changes
lgtm, kindly resolve your conflicts so we can merge this

2023-11-02 08:02 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jump-block.jsplumb.ts
> +    anchor: [0,0.13,0,1]
Lets leave this as 'Left' for now

2023-11-02 13:17 UTC, randy-kip commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jump-block.jsplumb.ts
> +    anchor: [0,0.13,0,1]
Done.

2023-11-14 08:39 UTC, LemmyMwaura approved these changes

2023-11-14 08:39 UTC, merged