:lipstick:Video input block redesign
italanta/elewa pull request #716
Opened 2023-10-13 18:51 UTC by Dancunrandy

# Description

Re-designed input video  block

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)
![Screenshot from 2023-10-13 21-41-48](https://github.com/italanta/elewa/assets/73400072/e7fa7213-7283-487f-ad81-504bba7d9441)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-02 08:07 UTC, LemmyMwaura requested changes
Update your PR desc, Sync your changes then resolve conflicts

2023-11-02 08:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-input-block.jsplumb.ts
>    });
remove this second jsplumb

2023-11-02 08:07 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.html
> +		<!-- <app-default-option-field [jsPlumb]="jsPlumb" [blockFormGroup]="videoInputForm"></app-default-option-field> -->
Leave the default option for now.

2023-11-02 11:51 UTC, Dancunrandy commented
@LemmyMwaura , resolved conflicts and added the default option

2023-11-14 08:20 UTC, LemmyMwaura commented
Closing this as its been resolved

2023-11-14 08:20 UTC, closed without merging