Document block
italanta/elewa pull request #717
Opened 2023-10-13 19:45 UTC by kiplangat01

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-02 08:10 UTC, LemmyMwaura requested changes
Sync your changes

2023-11-02 08:10 UTC, LemmyMwaura commented on apps/conv-learning-manager/src/assets/i18n/en.json
> +>>>>>>> 8cb27d53dec924c58b28fa27ef681ebdfb99c03f
Your PR has merge lines. This shouldn't be present

2023-11-02 08:10 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-card/chat-card.component.ts
> +              break;
Chats-related changes shouldn't be present. Kindly sync as this change was removed.

2023-11-14 12:34 UTC, kiplangat01 commented
i have made a new pr #812 to solve this issue

2023-11-14 12:40 UTC, kiplangat01 commented
i have made a new pr https://github.com/italanta/elewa/pull/812 to solve this issue

2023-12-06 10:32 UTC, LemmyMwaura commented
Closing this as it's been resolved.

2023-12-06 10:32 UTC, closed without merging