List question block redesign block redesign #626
italanta/elewa pull request #718
Opened 2023-10-14 00:11 UTC by Mutagah

# Description

This PR updates the UI of the list question block.

Fixes #626

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

![Screenshot from 2023-10-14 03-09-24](https://github.com/italanta/elewa/assets/106149210/231c8ae5-e295-43fd-b68e-5a2a6ef9e64b)

![Screenshot from 2023-10-14 03-10-20](https://github.com/italanta/elewa/assets/106149210/39441914-da08-4bb5-9b8b-8436b9835be9)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-11-02 08:13 UTC, LemmyMwaura requested changes
Sync your changes then request a review

2023-11-02 08:13 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/list-block.jsplumb.ts
> +    anchor: [0, 0.10, 0, 1],
Lets leave this as 'Left'

2023-11-02 15:00 UTC, Mutagah commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/list-block.jsplumb.ts
> +    anchor: [0, 0.10, 0, 1],
> Lets leave this as 'Left'

Changes requested have been addresses

2023-11-30 14:11 UTC, LemmyMwaura approved these changes
👍 awesome work

2023-11-30 14:11 UTC, merged