Document block redesign block redesign #640
italanta/elewa pull request #719
Opened 2023-10-15 11:20 UTC by thadeusdev

Fixes #640

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)e

# Screenshot (optional)
![Screenshot from 2023-10-15 14-18-03](https://github.com/italanta/elewa/assets/109853680/eeca3226-535c-4fd7-b1d8-dbe5aea1c708)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings

2023-11-02 08:17 UTC, LemmyMwaura requested changes
sync your changes and then resolve conflicts.

2023-11-02 08:17 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts
> +    anchor: [0, 0.11, 0, 1],
Lets leave this as 'Left'

2023-11-02 08:17 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.html
> +      <div
fix your indents.

2023-11-02 08:17 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.ts
> +    else if (
same here. Don't indent files you haven't worked on. This destroys the git history as it makes it seem like you worked on this. Just something to keep in mind

2023-11-02 20:27 UTC, thadeusdev commented on libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.html
> +      <div
fixed this. thanks for the heads up

2023-11-02 21:19 UTC, thadeusdev commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts
> +    anchor: [0, 0.11, 0, 1],
noted. thank you the heads up

2023-11-16 06:58 UTC, LemmyMwaura commented
Solve conflicts

2023-12-06 10:32 UTC, LemmyMwaura commented
Closing this as it's been resolved.

2023-12-06 10:32 UTC, closed without merging