Video input block redesign block redesign #644
italanta/elewa pull request #726
Opened 2023-10-17 20:26 UTC by thadeusdev

# Description

- Replaced video icon with svg
- Replaced menu ellipsis icon with svg
- styled the header
- styled the input field and text
- Re-positioned jsPlumb

Fixes #644

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings

2023-11-02 12:42 UTC, LemmyMwaura requested changes
Sync and resolve conflicts

2023-11-02 12:42 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-input-block.jsplumb.ts
> +    anchor: [0, 0.2, 0, 0],
have this as "Left"

2023-11-02 22:11 UTC, thadeusdev commented
Hi, I have the requested changes. Thank you for review

2023-11-14 08:20 UTC, LemmyMwaura commented
Closing this as its been resolved but good work

2023-11-14 08:20 UTC, closed without merging

2023-11-15 09:26 UTC, thadeusdev commented
Noted.