Video-block-redesign-block-redesign-643
italanta/elewa pull request #734
Opened 2023-10-18 09:56 UTC by philipNgungi037

# Description

The PR redesigns the video block. 
- Changing icons to svg.
- change js plum end-point.
- increase border smoothness.
- remove border outline.

Fixes #643

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![video-block](https://github.com/italanta/elewa/assets/111140962/207d3653-b442-4a45-b473-7dd8d7a00dde)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-02 12:45 UTC, LemmyMwaura requested changes

2023-11-02 12:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts
> +    anchor:  [0, 0.11, 0, 1],
have this as "Left"

2023-11-02 12:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.html
> -    <app-default-option-field [jsPlumb]="jsPlumb" [blockFormGroup]="videoMessageForm"></app-default-option-field>
Add the default option back

2023-11-03 13:54 UTC, philipNgungi037 commented
I have made changes. @LemmyMwaura

2023-11-14 08:15 UTC, LemmyMwaura commented
> I have made changes. @LemmyMwaura

The default option is still missing.

2023-11-16 08:13 UTC, LemmyMwaura commented
Closing as it's been resolved

2023-11-16 08:13 UTC, closed without merging