Conditional block redesign block redesign #636
italanta/elewa pull request #768
Opened 2023-10-19 23:34 UTC by thadeusdev

# Description

- changed font awesome conditional icon and used the svg conditional icon.
- changed the angulat material select drop down with the vanila HTML select and chevron-down svg icon. styled background and border-radius.
- swapped the position of square custom select and label and styled them so that it displays check mark when clicked.
- styled "type variable" input and "Add Option"button  

Fixes #636

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![screen-shot-conditional](https://github.com/italanta/elewa/assets/109853680/10a85f7c-84cc-4367-9b25-e517de4c0c42)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-11-02 13:59 UTC, LemmyMwaura requested changes
Sync your changes and resolve conflicts

2023-11-02 13:59 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/conditional-block.jsplumb.ts
> +    anchor: [0, 0.13, 0, 1],
Leave this as left or right for now

2023-11-02 13:59 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.html
> +          class="assess-label"
Avoid indenting, when saving your files (codebase-specific rule).

2023-11-02 18:58 UTC, thadeusdev commented on libs/features/convs-mgr/stories/blocks/library/conditional-block/src/lib/component/conditional-block/conditional-block.component.html
> +          class="assess-label"
Noted. i have made the requested changes. Thank you so much

2023-12-06 10:31 UTC, LemmyMwaura commented
Closing this as it's been resolved.

2023-12-06 10:31 UTC, closed without merging