:art: ci: Image input block redesign block redesign #639
italanta/elewa pull request #771
Opened 2023-10-24 11:11 UTC by thadeusdev

# Description

- changed image icon with the lighter version of it in svg.
- Adjusted font size and font weight for the block title.
- changed the ellipsis-v icon with the light version of its svg.
- styled the input field i.e background color, border-radius, font-weight, font-size and set outline to none.
- removed the hr tag that was adding an extra horizontal line.
- refactored jsPlumb

Fixes #639

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-10-24 14-07-40](https://github.com/italanta/elewa/assets/109853680/b4a277cd-b52f-428f-8eb2-82a3a57c2910)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-11-02 14:00 UTC, LemmyMwaura requested changes
Sync the latest changes and then resolve conflicts. Also, kindly edit your PR scope on your title as this is a design feature and not ci related.

2023-11-02 14:00 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-input-block.jsplumb.ts
> +    anchor: [0, 0.2, 0, 0],
Have this as 'Left'

2023-11-02 18:16 UTC, thadeusdev commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-input-block.jsplumb.ts
> +    anchor: [0, 0.2, 0, 0],
Noted. I have done as advised. Thank you for the heads up 🙏

2023-11-16 08:06 UTC, LemmyMwaura commented
@thadeusdev resolve conflicts so we can merge

2023-11-16 12:56 UTC, thadeusdev commented
conflicts resolved

2023-12-01 09:57 UTC, LemmyMwaura approved these changes

2023-12-01 09:57 UTC, merged