:lipstick: feat: Sticker block redesign block redesign #638
italanta/elewa pull request #772
Opened 2023-10-24 13:50 UTC by thadeusdev

# Description

- changed the stick-note icon and using its svg equivalent.
- Styled the font-weight and font-size for the block-title.
- changes ellipsis-v expand menu icons and used its equivalent svg.
- Changed the Plus icon to stick note svg and styled it including it background color and border radius(in rem).
- Styled/redesigned sticker link input field.
- redesigned and positioned jsPlumb

Fixes #638

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-10-24 16-47-57](https://github.com/italanta/elewa/assets/109853680/9c10a3cc-ffda-45ab-976a-452b42f9890e)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warning dependent changes have been merged and published in downstream modules

2023-11-03 06:10 UTC, LemmyMwaura requested changes
Sync the latest changes and then resolve conflicts. Also, kindly edit your PR scope on your title as this is a design feature and not ci related.

2023-11-03 06:10 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.html
> -				<i class="fas fa-plus"></i>
Turn off your indents when saving @thadeusdev

2023-11-06 19:49 UTC, thadeusdev commented on libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.html
> -				<i class="fas fa-plus"></i>
noted. Thank you for recommendation 🙏

2023-11-16 07:19 UTC, LemmyMwaura commented
Closing this as its been resolved

2023-11-16 07:19 UTC, closed without merging