Email block redesign #623
italanta/elewa pull request #781
Opened 2023-10-27 12:18 UTC by PerisOduol618

# Description

The "Email Block" component in the app is redesigned to enhance its usability and visual appeal.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #623

# Screenshot (optional)
![image](https://github.com/italanta/elewa/assets/67086872/49b117f5-4c84-4107-95aa-12bf8c74229a)

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation

2023-11-03 08:31 UTC, LemmyMwaura requested changes
Sync then resolve conflicts kindly.

2023-11-03 08:31 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts
> +    anchor: [0, 0.23, 1, 0],
Let's leave this as "Left" for now

2023-11-03 14:10 UTC, PerisOduol618 commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts
> +    anchor: [0, 0.23, 1, 0],
@LemmyMwaura Done

2023-11-14 06:11 UTC, LemmyMwaura commented
Closing this as it's been resolved by Dennis. His implementation was first but good work

2023-11-14 06:11 UTC, closed without merging