🎨💄 CLM-326-Change button text to "edit" #788
italanta/elewa pull request #800
Opened 2023-11-01 07:53 UTC by Paul-ike

# Description

Changed the button text from "Edit company information" to "Edit"

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #788 🎨💄 CLM-326-Change button text to "edit"

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

![Screenshot](https://drive.google.com/uc?export=download&id=1pv-BT9nlA_qb94HlSfCgjtswf9R4DBr8)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-03 09:18 UTC, LemmyMwaura requested changes

2023-11-03 09:18 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
>            .menu-icon {
This changes should not be part of this issue

2023-11-03 10:47 UTC, Paul-ike commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
>            .menu-icon {
I have rectified the changes

2023-11-10 14:21 UTC, closed without merging

2023-11-10 14:22 UTC, LemmyMwaura commented
Closed as completed. Thanks