:art: add dropdown to collapse chats and templates into messaging
italanta/elewa pull request #802
Opened 2023-11-01 08:36 UTC by dennis-mburu

# Description
This PR makes the messaging menu clickable and also nests the chats and messages templates under it so that when the user clicks on the messaging menu, the nested items are then visible so that the user can then navigate wherever they wish. 
It also fixes the chats and templates misalignment whenever the menu is collapsed

Fixes #787

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
https://github.com/italanta/elewa/assets/65117575/aefc604b-4bb7-45d4-8d33-a4a9cc19e895

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2023-11-03 09:19 UTC, LemmyMwaura approved these changes

2023-11-03 09:20 UTC, LemmyMwaura requested changes
Resolve conflicts and then we can merge.

2023-11-03 10:40 UTC, dennis-mburu commented
Conflicts resolved. Kindly review @LemmyMwaura

2023-11-04 14:06 UTC, dennis-mburu commented
> Resolve conflicts and then we can merge.

Conflicts resolved and dropdown icon implemented. Kindly review @LemmyMwaura

2023-11-10 14:18 UTC, LemmyMwaura approved these changes

2023-11-10 14:18 UTC, merged