🚧 🐎 [WIP] Processing message and return next block in the story
italanta/elewa pull request #81
Opened 2022-09-27 08:20 UTC by ReaganCn

# Description

Part of issue #38 
This implementation includes the below:
- An addMessage handler that adds the incoming message to a firebase colllection
- A registerUser handler that registers the chat specific information of the user e.g. story id, phone number, org id
- A processMessage handler that listens to `document.create` in the messages collection and returns the next block 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-27 13:13 UTC, jrosseel requested changes

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +  async end(chatInfo: ChatInfo, tools: HandlerTools){
define return type and put { on new line

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +    await chatBotRepo$.chatStatus().updateChatStatus(chatInfo, ChatStatus.Ended, this._platform)
nested object accessor

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +  async jumpToBlock(blockId: string, chatInfo: ChatInfo, tools: HandlerTools){
Keep clarifying fn comments

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +  async handleDuplicates(msg: Message, tools: HandlerTools): Promise<boolean>{
This is not a good approach for handling race conditions. Remove. Later we'll add transaction locks to this

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/match-input/match-input.service.ts
> +export class MatchInputService {
This is good to keep in a strategy pattern!

Move to seperate package

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/question-block.service.ts
> +export class QuestionMessageService implements NextBlockInterface {
Move to seperate package and rename NextBlockInterface to BlockPlayer

This then becomes QuestionBlockPlayer

Consider turning BlockPlayer into an abstract class so you can utilise template method for pre-processing (such as input preprocessing) and logging

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/question-block.service.ts
> +export class QuestionMessageService implements NextBlockInterface {
Template method would mean your public method (in this case getNextBlock [but should be renamed ;)]) is exposed but is final

Final means it cannot be overriden by subclasses.

The public method would pre- and post-process, then call a protected abstract method called e.g. "determineNextBlock" with defined input and output signature.

The classes inheriting from BlockPlayer need to implement this determineNextBlock with their own logic

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/text-block.service.ts
> +export class TextMessageService implements NextBlockInterface {
TextBlockPlayer

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/next-block.factory.ts
> +export class NextBlockFactory {
A BlockPlayerFactory is necessary indeed

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/next-block.factory.ts
> +export class NextBlockFactory {
Would also be useful to consider a DI injector for this case

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/next-block.factory.ts
> +export class NextBlockFactory {
https://blog.logrocket.com/top-five-typescript-dependency-injection-containers/

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/next-block.interface.ts
> +export interface NextBlockInterface {
Abstract class with template-method pattern

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/stores/chatbot.store.ts
> +export class ChatBotStore {
Cannot be named store

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/stores/chatbot.store.ts
> +export class ChatBotStore {
I do not like this pattern. Figure out a better, more domain-driven way

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/chatbot/src/lib/stores/lib/blocks-connections.store.ts
> +export class BlockConnectionsStore {
Cannot be called store

2022-09-27 13:13 UTC, jrosseel commented on libs/functions/conversations/onboarding/src/lib/register-user.handler.ts
> + * Register User Handler. Records all onboarding information of a user
Provide more context on when this would be used and the "why" of the component

2022-09-27 13:13 UTC, jrosseel commented on libs/state/convs-mgr/stories/blocks/src/lib/services/anchor-story-blocks.service.ts
> +export class AnchorBlockService {
Remove. Since this a constant we don't need state for it

2022-11-03 12:00 UTC, ReaganCn commented
All requested changes addressed in PR #124

2022-11-03 12:00 UTC, closed without merging