💄 Fixed the Left Side Block-List Stylings For the Editors Page
italanta/elewa pull request #815
Opened 2023-11-03 05:39 UTC by Beryl-ajuoga

# Description

For this, I fixed the styling on the blocks list on the left side by making it uniform from top to bottom  to prevent cutting out and leaving a white space underneath whenever a user zooms out . 

This is the previous UI 
![image](https://github.com/italanta/elewa/assets/99467660/f151bc3a-ccff-4adf-a88d-99c3989b079b)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Screenshot (optional)
This is the current UI after the change
![image](https://github.com/italanta/elewa/assets/99467660/a13d05fd-53c9-4f04-8e66-93f28c2ba868)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] New and existing unit tests pass locally with my changes

2023-11-15 07:27 UTC, ReaganCn commented
@LemmyMwaura please review

2023-11-16 07:18 UTC, LemmyMwaura requested changes
This changes the bg color of the editor page but you should make the blocks-library component cover the entire height.

2023-11-16 11:19 UTC, Beryl-ajuoga commented
> This changes the bg color of the editor page but you should make the blocks-library component cover the entire height.

Fixed

2023-11-16 12:18 UTC, LemmyMwaura approved these changes

2023-11-16 12:19 UTC, merged