💄 Created Modal to Add And Update WhatsApp And Messenger Channels #CLM-92
italanta/elewa pull request #824
Opened 2023-11-03 13:24 UTC by JAPHETHNYARANGA

# Description

Here  i have created a front-end modal to add and update channels for both whats-App and messenger

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-11-03 16-18-57](https://github.com/italanta/elewa/assets/71229825/d6959caf-be8c-4897-b0d6-0700f4ea4de5)
![Screenshot from 2023-11-03 16-19-23](https://github.com/italanta/elewa/assets/71229825/72cb1468-46f0-4cec-b2ec-e6dd1dec8dec)
![Screenshot from 2023-11-03 16-20-56](https://github.com/italanta/elewa/assets/71229825/5a3ba19c-9fe2-4883-9827-b42b88de2dae)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-11-06 09:34 UTC, LemmyMwaura requested changes

2023-11-06 09:34 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.ts
> +  continueButtonText = 'Continue';
use an if check to switch between the text in the template. This will make this property unnecessary which is the best approach.

2023-11-06 09:34 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.html
> +      </form>
Process the form logic. Use Reactive forms

2023-11-06 09:34 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.html
> +            <input type="text" placeholder='{{"COMPANY-INFORMATION.CHANNEL-MODAL.BOT-PHONE-NUMBER-ID" | transloco}}' id="fname" name="fname" ><br>
also here. Process form

2023-11-06 09:34 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.ts
> +      this.showMessengerForm = false;
You only need one of this boolean checks. If it's showWhatsapp then in your template you can show messenger if `*ngIf="!showWhatsAppForm"`

2023-11-06 09:34 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.html
> -              </button>
Company-related updates have bled into this PR. something to take into account.

2023-11-08 08:22 UTC, ReaganCn requested changes
A few changes needed. Please see my comments and incorporate them throughout your code

2023-11-08 08:22 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.ts
> +  showButtons = false;
No need to assign these variables to false. An undefined value is also false. Read about falsy values. So declare them as boolean and leave it at that

2023-11-08 08:22 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/interfaces/channneldetails.interface.ts
> +export interface CardElement{
There is an interface for CommunicationChannel. You should use it instead of this

2023-11-08 08:22 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.scss
> +            font-size: 20px;
Dont use pixels for font size

2023-11-08 08:22 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.scss
> +        color: #3E788A;
Use variables for colors. All colors are defined in _variables.scss. If a color is missing you can add it there. Helps have a central place to manage the whole platform theme

2023-11-08 08:22 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.scss
> +                font-size: 16px;
Here too

2023-11-09 08:05 UTC, ReaganCn requested changes

2023-11-09 08:05 UTC, ReaganCn commented on libs/elements/theming/_variables.scss
> +  --convs-mgr-cowhitelor-primary-: #fff;
Typo?

2023-11-09 08:05 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/channel-form-modal/channel-form-modal.component.scss
> +        color: #3E788A;
Color variables

2023-11-14 07:12 UTC, ReaganCn requested changes
- Update the translations
- Remove first story column

2023-11-14 07:32 UTC, LemmyMwaura requested changes

2023-11-14 07:32 UTC, LemmyMwaura commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/channel-form-modal/channel-form-modal.component.ts
> +
Some values will be lost as both channels have different values specific to them. You can create both forms separately from an external providers file (as done in blocks) and just equate the form to your channels form propery or have a switch case for your form on the template. 

You can check the blocks form to understand how this has been done.

2023-11-14 08:33 UTC, JAPHETHNYARANGA commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.ts
> +];
this is an old data for testing, currently not available on the recent files @LemmyMwaura

2023-11-15 05:39 UTC, ReaganCn approved these changes

2023-11-15 05:45 UTC, LemmyMwaura approved these changes

2023-11-15 05:45 UTC, merged