Location block
italanta/elewa pull request #840
Opened 2023-11-08 12:06 UTC by Dancunrandy

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-16 17:37 UTC, Dancunrandy commented
@LemmyMwaura , this is the one i closed by mistake and had to create new PR

2023-11-21 11:45 UTC, LemmyMwaura requested changes

2023-11-21 11:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/utils/transformers/location-block.jsplumb.ts
> +  // });
remove dead code

2023-11-21 11:45 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/location-message-block/src/lib/components/location-block/location-block.component.html
> +		<app-default-option-field [jsPlumb]="jsPlumb" className="app-default-option-field" [blockFormGroup]="locationMessageForm">
No need for this className

2023-11-21 12:27 UTC, Dancunrandy commented
@LemmyMwaura have updated the code

2023-11-21 14:39 UTC, LemmyMwaura reviewed
Small change left, Ping me when you are done.

2023-11-21 14:39 UTC, LemmyMwaura commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/utils/transformers/location-block.jsplumb.ts
> +    anchor: [0, 0.1,0,1],
Let's leave this as "Left" as it was for now

2023-11-21 14:46 UTC, Dancunrandy commented
@LemmyMwaura , have restored anchor position

2023-12-19 17:28 UTC, Dancunrandy commented
@LemmyMwaura PR updated.

2024-03-22 09:43 UTC, closed without merging