💄Fixed Unblock User on the  Chats Page#CLM-246
italanta/elewa pull request #843
Opened 2023-11-14 05:59 UTC by Beryl-ajuoga

# Description
I added a check to ensure that the user's current position includes a  communication channel then before that incorporated a method to hide the spinner before it so a to remove the recurrent long spinning

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

2023-11-14 07:02 UTC, ReaganCn requested changes

2023-11-14 07:02 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +      if(!this.currentPosition.CommunicationChannel){
This check won't work as communication channel does not exist on the current position. What can be done is to check the end user id which is formatted this way: `w_1_254XXXXXXXX`, where the middle number(1) is the number of the channel. So you will extract the middle number and check if a channel exists with that number. 

Because if you observe the communication channel interface, there is an 'n' property with represents the channel number. The same number is included in the end user id

2023-11-14 07:04 UTC, Beryl-ajuoga commented on libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
> +      if(!this.currentPosition.CommunicationChannel){
Noted

2023-11-15 06:13 UTC, Beryl-ajuoga commented
Opened a new PR #847

2023-11-15 06:13 UTC, closed without merging