Add ability to filter learners by classroom #862
italanta/elewa pull request #864
Opened 2023-11-18 21:02 UTC by dennis-mburu

# Description

This PR adds the ability to filter learners by class on the learners page.

Fixes #862 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

https://github.com/italanta/elewa/assets/65117575/dbb75002-3887-4e96-a2ac-3bd305787dd5

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-11-21 08:15 UTC, LemmyMwaura requested changes
Good work on this but you should customise it to work by updating the filterPredicate method that matTable comes with. This will allow us to add more complex filters

2023-11-21 12:23 UTC, dennis-mburu commented
> Good work on this but you should customise it to work by updating the filterPredicate method that matTable comes with. This will allow us to add more complex filters

Changes Implemented. Kindly review @LemmyMwaura

2023-11-22 05:46 UTC, LemmyMwaura requested changes

2023-11-22 05:46 UTC, LemmyMwaura commented on libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts
> +  }
When filter === 'Default", return users that have no class set. class = ""

2023-11-22 05:46 UTC, LemmyMwaura commented on libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts
>      }
Mode doesn't get passed here. Pass it in your custom filter predicate.

2023-11-22 07:58 UTC, dennis-mburu commented
Both changes addressed. Kindly review @LemmyMwaura

2023-11-28 08:07 UTC, LemmyMwaura requested changes
Very good work on this. But the new update creates a lot more complexities than i would want on the search and the default search doesn't work. So let's just revert to our ealier implementation. I'll then find a way to customise it to use the filter predicate. 

For now make sure it work cleanly but with the initial implementation.

2023-12-19 13:13 UTC, LemmyMwaura approved these changes

2023-12-19 13:14 UTC, merged