💄Added Delete Functionality to the End Block #CLM-325
italanta/elewa pull request #866
Opened 2023-11-20 07:09 UTC by Beryl-ajuoga

# Description
Added the delete functionality to the end block on user story

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2023-11-21 07:40 UTC, LemmyMwaura requested changes
The functionality has not yet been added. This needs to have some logic to delete the block. But also attach a screenshot in your readme.

2023-11-22 05:26 UTC, ReaganCn requested changes
Good implementation but you can update the styling of the start and endblock to match the design. Currently with the old design it doesnt look great.

2023-11-22 05:29 UTC, Beryl-ajuoga commented
> The functionality has not yet been added. This needs to have some logic to delete the block. But also attach a screenshot in your PR description.

okay

2023-11-22 05:30 UTC, Beryl-ajuoga commented
> The functionality has not yet been added. This needs to have some logic to delete the block. But also attach a screenshot in your PR description.

okay

2023-11-22 05:30 UTC, Beryl-ajuoga commented
> Good implementation but you can update the styling of the start and endblock to match the design. Currently with the old design it doesnt look great.

okay

2023-11-27 08:34 UTC, ReaganCn commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
> +                    </app-end-anchor>
Receive the delete event over here and then call the delete method in this component with the necessary parameters. [https://ultimatecourses.com/blog/component-events-event-emitter-output-angular-2](link)

2023-12-01 06:51 UTC, LemmyMwaura approved these changes

2023-12-01 06:52 UTC, merged