close delete modal when you delete
italanta/elewa pull request #872
Opened 2023-11-21 13:49 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-28 08:26 UTC, LemmyMwaura requested changes
This is a short cut that breaks more parts that it does fix.

2023-11-28 11:59 UTC, levy-web commented
@LemmyMwaura fixed changes kindly check

2023-11-29 07:59 UTC, LemmyMwaura requested changes

2023-11-29 07:59 UTC, LemmyMwaura commented on libs/features/convs-mgr/modules/src/lib/components/modules-lessons-grid-view/modules-lessons-grid-view.component.ts
> +        mode: DeleteElementsEnum.Story, element: story, parentElement:this._botsModulesServ$.getBotModuleById(story.parentModule ?? "")
Just pass the id. We don't need the entire bot. `parentElement: story.parentModule`

2023-12-08 13:37 UTC, LemmyMwaura requested changes

2023-12-08 13:37 UTC, LemmyMwaura commented on libs/features/convs-mgr/modules/src/lib/components/modules-lessons-grid-view/modules-lessons-grid-view.component.ts
> +    console.log(this._router$$.navigate(['stories', id]))
remove log statement.

2023-12-13 05:40 UTC, closed without merging