💄Fixed-Settings-Label#336
italanta/elewa pull request #873
Opened 2023-11-21 15:43 UTC by Beryl-ajuoga

# Description
Changed the Label Admin Settings to Settings 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-11-22 05:28 UTC, ReaganCn requested changes

2023-11-22 05:28 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/main/src/lib/pages/settings-page/settings-page.component.html
> +      <div class="admin-header">Settings</div>
Please use multi-lang

2023-11-22 06:24 UTC, Beryl-ajuoga commented on libs/private/features/convs-mgr/settings/main/src/lib/pages/settings-page/settings-page.component.html
> +      <div class="admin-header">Settings</div>
> Please use multi-lang

Fixed

2023-11-22 06:39 UTC, ReaganCn requested changes

2023-11-22 06:39 UTC, ReaganCn commented on apps/conv-learning-manager/src/assets/i18n/en.json
> +        "NO-THANKS": "No Thanks"
Here, you have reverted some changes that were made by someone else in this issue: 
<img width="809" alt="image" src="https://github.com/italanta/elewa/assets/34684844/936a4dd5-7abf-4c40-8c8a-c889256a64e7">

2023-11-27 11:15 UTC, ReaganCn approved these changes

2023-11-27 11:15 UTC, merged