💄  mask surveys and analytics tabs #Clm 338
italanta/elewa pull request #880
Opened 2023-11-23 21:19 UTC by JAPHETHNYARANGA

# Description

In this issue , i have implements a flags feature, where items in the sidenav can be added or deleted on the fly.

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-11-28 06:52 UTC, LemmyMwaura commented on apps/conv-learning-manager/src/assets/featureFlags.json
> +}
Have this inside a folder. Let's name it fflags

2023-11-28 07:39 UTC, LemmyMwaura requested changes
👍 Good job so far.

A few updates left. Also, add a route guard for the feature flags as I can manually change the routes to features that are marked as false.

2023-11-28 07:39 UTC, LemmyMwaura commented on libs/elements/base/feature-flags/src/lib/service/feature-flags.service.ts
> +    });
Move this logic into a method called init which returns the subscription. Then call it in the sidemenu when you import this service. This will allow you to clean this subscription efficiently.

2023-11-28 07:39 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +              <a (click)="navigateToHome()">
Is there a reason the routerLinks have been moved to the ts file? If not just leave them on the template.

2023-11-28 07:39 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +                  </span>
This should also be shown depending on the feature flag. if false show the coming soon.

2023-11-28 07:39 UTC, LemmyMwaura commented on libs/elements/base/feature-flags/src/lib/elements-base-feature-flags.module.ts
> +  providers: [FeatureFlagsService],
The feature is already provided in the root. so no need to have it in this providers list.

2023-11-28 07:39 UTC, LemmyMwaura commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> +import { FeatureFlagsService } from 'libs/elements/base/feature-flags/src/lib/service/feature-flags.service';
Import this from the aliased path.

2023-11-30 18:00 UTC, JAPHETHNYARANGA commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +              <a (click)="navigateToHome()">
I have moved the links to make the code look more cleaner

2023-12-05 11:46 UTC, LemmyMwaura approved these changes

2023-12-05 11:46 UTC, merged