🎨 integrate document type message on chats list
italanta/elewa pull request #881
Opened 2023-11-27 05:20 UTC by darlene9497

# Description

This pull request addresses the issue of integrating the document message on the chats list.

Fixes #836 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
![Screenshot from 2023-11-27 08-15-25](https://github.com/italanta/elewa/assets/117742892/7bf63038-bfa1-4905-ace3-a5e8ffc96bd4)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-11-28 06:50 UTC, LemmyMwaura requested changes
Very good attempt

2023-11-28 06:50 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/messaging/src/lib/components/chat-message/chat-message.component.ts
> +import { ICONS_AND_TITLES } from '../../../../../../stories/blocks/library/main/src/lib/assets/icons-and-titles';
This import is too relative. Export the file from it's module so you can use the aliased path to import it.

2023-11-29 04:27 UTC, darlene9497 commented on libs/features/convs-mgr/conversations/messaging/src/lib/components/chat-message/chat-message.component.html
> +      </div>
@LemmyMwaura I have done this but passing it as app-resource-message, only the icons are displaying. Kindly advise

2023-11-30 14:13 UTC, LemmyMwaura commented on libs/features/convs-mgr/conversations/messaging/src/lib/components/chat-message/chat-message.component.html
> +      </div>
Okay, i'll test your branch tomorrow then give you feedback.

2023-12-19 12:22 UTC, closed without merging