🐛 ⚡ (Bugfix) Bots no longer created when clicking create button #74
italanta/elewa pull request #89
Opened 2022-10-05 04:22 UTC by AnnaL001

# Description

I have edited the modal "name" form input to have a filled-in default value by using the ReactiveFormsModule. Aside from that, I have added translations for the modal as specified. Finally, I have updated the create bot functionality to allow for the creation of bots. 

Fixes #74 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Screenshot (optional)
![Screenshot from 2022-10-05 02-53-21](https://user-images.githubusercontent.com/43697008/193977568-89114cce-a0d5-443e-abd6-a66657e3be80.png)
![Screenshot from 2022-10-05 02-54-29](https://user-images.githubusercontent.com/43697008/193979434-6a6d56cf-2cdb-4805-983c-0bc389cfa6b9.png)
![Screenshot from 2022-10-05 02-52-44](https://user-images.githubusercontent.com/43697008/193977741-d8ac005a-1564-48d8-90c9-3317fcde9df4.png)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2022-10-05 06:58 UTC, ReaganCn requested changes
Congrats on your first PR 🎉, and a good first attempt. I have requested some straight forward changes on your code. Please see my comments below.

2022-10-05 06:58 UTC, ReaganCn commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.ts
> +      height: '480px',
You can move this styling to the CreateModalComponent scss.

2022-10-05 06:58 UTC, ReaganCn commented on libs/features/convs-mgr/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts
> +  botForm = this._formBuilder.group({
Wrap the botForm formBuilder in a method and place it below the constructor. This ensures clean code.

2022-10-05 06:58 UTC, ReaganCn commented on libs/features/convs-mgr/home/src/lib/services/new-story.service.ts
>        name = uniqueNamesGenerator({ dictionaries: [adjectives, colors, animals] });
Call the generate name method here instead of `uniqueNamesGenerator`

2022-10-05 12:42 UTC, AnnaL001 commented on libs/features/convs-mgr/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts
> +  botForm = this._formBuilder.group({
Change has been made

2022-10-06 00:06 UTC, AnnaL001 commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.ts
> +      height: '480px',
Change has been made

2022-10-07 06:04 UTC, ReaganCn approved these changes
Good job 💪!!!

2022-10-12 14:20 UTC, merged