💄 Creted a new Variables section for header field #CLM-319
italanta/elewa pull request #928
Opened 2024-01-10 05:09 UTC by JAPHETHNYARANGA

# Description

Here i have created a new field to hold header variables

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2024-01-10 08:32 UTC, ReaganCn requested changes

2024-01-10 08:32 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
> +    console.log("header variable is "+ this.newHeaderVariables$)
Remove this console.logs

2024-01-10 08:32 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
> +  newHeaderVariables: any[] = [];
Add a limit for the maximum variables a header can have to be 1

2024-01-10 08:32 UTC, ReaganCn commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
This file has become too large. Move some of the repetitive logic to a /utils/ folder and create a file there. Then export the function to use here.

2024-01-12 10:13 UTC, JAPHETHNYARANGA commented on libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
> +  newHeaderVariables: any[] = [];
used *ngIf="newHeaderVariables.length < 1"  in the template to prevent more than one entry, incase more than one is needed, only this code will change

2024-01-12 13:18 UTC, ReaganCn approved these changes

2024-01-12 13:20 UTC, merged