Copy block #15
italanta/elewa pull request #93
Opened 2022-10-06 08:02 UTC by IanKoech

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)
<img width="956" alt="New PR" src="https://user-images.githubusercontent.com/66770693/194254143-ad21f0e0-33e1-41a3-9918-d2f6064bac90.PNG">

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-12 14:28 UTC, jrosseel requested changes
Still some changes ahead

2022-10-19 07:27 UTC, IanKoech commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +    this.blocksGroup.push(this.blockFormGroup);
I had removed the `private` access modifier of the _createBlock function in order to call the function from the block.component.ts file, will this change need to be undone

2022-11-01 07:29 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +    this.blockCopy = ___cloneDeep(this.block);
You'll have to reassign the blockId from the previous block otherwise you'll inject a new block with a similar ID to an existing one.

2022-11-15 07:52 UTC, IanOdhiambo9 requested changes

2022-11-15 07:52 UTC, IanOdhiambo9 commented on libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
This function should remain private

2022-11-15 07:52 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
> +    this.copyBlockService._createBlock(this.blockCopy);
while uniqueId is a great way to generate random values there could be chance the numeral generated has a value that matches one of the blocks especially if the story has a lot of them. At the moment block id is incremented by 1 every time a new block is added to the frame. We want to stick to that approach, what you need to do is get the number of blocks present in the frame then add 1 and assign that as the Id for the copied block.

2022-11-28 05:13 UTC, closed without merging