✨ 💄 Created menu dialog in bots card #CLM-130
italanta/elewa pull request #930
Opened 2024-01-17 20:45 UTC by JAPHETHNYARANGA

# Description

In this pr, i have created a menu dialog that enables user to connect bot to channel, to publish bot, to archive bot and to delete bot.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-19 12:50 UTC, ReaganCn requested changes

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-latest-courses/bots-list-latest-courses.component.ts
> +    this._dialog.open(ConnectToChannelModalComponent, dialogConfig);
Its much cleaner to use an object for the config. Like this example in the official documentation:

```
let dialogRef = dialog.open(UserProfileComponent, {
  height: '400px',
  width: '600px',
});
```

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/courses/course-module-item/course-module-item.component.ts
> +    this._dialog.open(ConnectToChannelModalComponent, dialogConfig);
Same here. Clean it up

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/services/bots-module.service.ts
> +export class BotsModuleService {
This class is a redundant since there is a bot state service to handle deletion and any other functions on a bot and there is a channel service for anything related to channels. So move the methods here to there respective services and delete this.

2024-01-19 12:50 UTC, ReaganCn commented on libs/model/convs-mgr/bots/src/lib/bots.interface.ts
> +  archived?: boolean;
isArchived for consistency

2024-01-19 12:50 UTC, ReaganCn commented on libs/model/convs-mgr/conversations/admin/system/src/lib/channel.interface.ts
> +   bot?:string
'linkedBot' - it's easier to know what it is for just by the name

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/services/bots-module.service.ts
> +  getMessengerChannels():Observable<CommunicationChannel[]>{
Instead of separate methods for each channel, just get all channels and then use a filter on the component level once someone has selected the type of channel. By component I mean the modal. Should be a multi-step modal like the one Lemmy created for creating a bot.

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts
> +      this._dialog.open(ChannelComponent, dialogConfig);
Clean this up too

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts
> +import { BotsModuleService } from '../../services/bots-module.service';
Order of imports

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts
> +export class ConnectToChannelModalComponent {
There should be only one component for publishing modal. So you should combine this and the Channel component modal.

It's called a multi-step component, where one step(usually a form) leads to the next one. An example is the create bot flow, where you create a bot, module and story under one modal.

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/channel/channel.component.ts
> +    if (this.data.selectedPlatform === PlatformType.WhatsApp) {
This is a repetition, because you are filtering and then checking again of the selected platform is whatsapp on the component. Refer to my comments on the service where you do the filtering and also about using one modal for selecting a channel and publishing.

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts
> +export class ConnectToChannelModalComponent {
Each form in each step can be a separate component to ensure clean code

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/channel/channel.component.ts
> +import { CommunicationChannel, PlatformType } from '@app/model/convs-mgr/conversations/admin/system';
Spacing between categories of imports

2024-01-19 12:50 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/courses/course-module-item/course-module-item.component.ts
> +  specificBot: Bot | any; /**adding undefined here since it is described that way in the store service, removing might break something, check on this */
This does not make sense. Remove the 'any'. If a property does not have a value, then it will be null which behaves like undefined.

2024-01-22 09:38 UTC, JAPHETHNYARANGA commented on libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-latest-courses/bots-list-latest-courses.component.scss
> +      position: absolute;
it will not, stick. it is absolute to its parent component. I have done that to reduce spacing between it and top componets, i think the spacing is caused by angular material

2024-01-22 11:22 UTC, JAPHETHNYARANGA commented on libs/features/convs-mgr/stories/home/src/lib/services/bots-module.service.ts
> +export class BotsModuleService {
The extra class helps to make the code cleaner and avoid making the store service interact directly with the component . The state service contains only the crud methods and this service now manipulates the data reusing the methods provided by the store service. If this is not as necessary, please give a feedback i delete it. Thank you

2024-01-22 12:15 UTC, JAPHETHNYARANGA commented on libs/features/convs-mgr/stories/home/src/lib/components/courses/course-module-item/course-module-item.component.ts
> +  specificBot: Bot | any; /**adding undefined here since it is described that way in the store service, removing might break something, check on this */
the reason is due to this like of code by lemmey    getBotModuleById(id: string): Observable<BotModule | undefined> {
    return this._botModuleStore$$.getOne(id);
  }  its in the "BotModulesStateService" file. thus i need to declare any since i am using the same function. If i change  without lemmy i might break things in the app.

2024-01-23 13:40 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts
> +export class ConnectToChannelModalComponent {
This is what I mean by multi-step and it is what you should use: https://material.angular.io/components/stepper/overview because it improves the user experience, groups all the steps into one component and allows you to separate the main components into several others ensuring clean code.

You can refer to the creation of the bot. It uses the same angular material stepper

2024-01-23 14:02 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/courses/course-module-item/course-module-item.component.ts
> +  specificBot: Bot | any; /**adding undefined here since it is described that way in the store service, removing might break something, check on this */
Then it should be 'BotModule | undefined' and not 'Bot | any'

2024-01-30 06:27 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/services/bots-module.service.ts
> +export class BotsModuleService {
That's not how clean code works. It's still redundant. You should move the methods here to the other state service. Because having two classes that basically have the same responsibility is confusing. And you now have to update both if in any case the logic of the bot module changes. So just delete it.

2024-01-30 11:03 UTC, ReaganCn approved these changes

2024-01-30 11:03 UTC, merged