Open a bot functionality #78
italanta/elewa pull request #94
Opened 2022-10-06 12:18 UTC by Nyash-Mauro

# Description

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

2022-10-07 06:17 UTC, ReaganCn commented
Please update the PR description accordingly. See example: https://github.com/italanta/elewa/pull/86

2022-10-13 12:25 UTC, ReaganCn requested changes
Congrats on your first PR. It woould be better if you used a hand cursor when someone hovers over the card to show that it is clickable

2022-10-13 12:25 UTC, ReaganCn commented on libs/elements/layout/page/src/lib/components/app-navbar/navbar.component.scss
> +  color: #3c3c3c;
Use theme color variables colors from _variables.scss. You can ask Trevin on how to do it

2022-10-17 06:50 UTC, ReaganCn approved these changes
Good work!

2022-10-17 07:49 UTC, Nyash-Mauro reviewed
Hello I've already made the changes

2022-10-17 07:49 UTC, Nyash-Mauro commented
Hello made the changes kindly check on the resolved conflict

2022-10-27 05:51 UTC, merged