🎨 {refactor }open bot functionality #78
italanta/elewa pull request #95
Opened 2022-10-06 13:57 UTC by faisoabdirisak

# Description

I have edited the bot card, when clicked the whole bot, it should open the bot.

Fixes # (issue) - 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-10-12 14:32 UTC, jrosseel requested changes

2022-10-13 07:12 UTC, jrosseel requested changes

2022-10-13 07:12 UTC, jrosseel commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.scss
> +@import "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css";
Remove this. Instead, merge main into your branch

2022-10-13 07:45 UTC, faisoabdirisak commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.scss
> +@import "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css";
Done it

2022-10-13 09:19 UTC, jrosseel requested changes

2022-10-13 09:19 UTC, jrosseel commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html
> +          {{story.name }} <span class="bot-number">(6 bots)</span>
Remove 6 bots constant

2022-11-01 07:37 UTC, closed without merging