🚧 🏇 [WIP] Creation of base bot engine
italanta/elewa pull request #96
Opened 2022-10-12 11:59 UTC by ReaganCn

# Description
### Part of issue #38

This PR contains implementation of the core process of the bot:

- Implements the process of receiving the message from various platforms e.g. whatsapp, telegrams and interpreting it 
    - Whatsapp Hook
    - Add message
- Implements a way of processing the message and getting the next block
   - Process message handler
- Implementing the process of inteprating the block and sending the message to the appropriate platform
   - Send Message handler

## Type of change
[ ] - [WIP] - Feature

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-12 15:41 UTC, jrosseel requested changes
Still a way to go ...

2022-10-12 15:41 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +    this._dialog.open(AddBotToChannelModal, {
To think through this flow

2022-10-12 15:41 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/providers/manage-channel-story-link.service.ts
> +export class ManageChannelStoryLinkService {
Clarifying comment on purpose

2022-10-12 15:41 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/providers/manage-channel-story-link.service.ts
> +  public addStoryToChannel(channel: BaseChannel)
Add comment to purpose and describing inputs

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/bot-users/src/lib/models/manage-bot-users.model.ts
> +export class ManageBotUsersModel
Comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/bot-users/src/lib/models/manage-bot-users.model.ts
> +  addUser(phoneNumber:string, channel:Platforms )
This would be better modelled using an abstract class and inversion of control

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/bot-users/src/lib/models/manage-bot-users.model.ts
> +  addUser(phoneNumber:string, channel:Platforms )
Put a factory in between

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> + * Processes the message and returns the next block.
Comment too vague

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> +    await this._sendMessage({msg: req, block: nextBlock}, tools)
Will the action always be to send a message? In my oponion it's the the processor to decide

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> +    // To later use a DI container to manage instances and dynamically inject approtiate dependencies
Yes please

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> +    if(!userActivity){
Why is this different?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> +    if(!userActivity){
Can this be interjected. 
```
if(!userActivity) { // to load user procedure }

// Continue normal flow
```

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/handlers/process-message.handler.ts
> +        const resp = await axios.post('https://europe-west1-ele-convl-manager-7cd0a.cloudfunctions.net/sendMessage', payload, {
Load from process.env

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/blocks.service.ts
> + * Contains all the required database flow methods for writing and reading blocks information
Comment inadequate

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/blocks.service.ts
> +  /** TODO: Remove after implementing a static block on front end */
Please implement

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/blocks.service.ts
> +    const firstConnection = await this._connDataService$.getConnBySourceId(channelInfo.storyId);
Reiterate comments here

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/channel-info.service.ts
> + * Contains all the required database flow methods for the ChatInfo collection
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/channel-info.service.ts
> +  private _docPath: string;
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/channel-info.service.ts
> +  async getChannelInfo<T>(phoneNumber: string): Promise<T> {
Comment?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/channel-info.service.ts
> +  async getChannels(): Promise<BaseChannel> {
Comment?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/chat-status.service.ts
> + * Contains all the required database flow methods for the chat-status collection
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/chat-status.service.ts
> +  async initChatStatus(channel: BaseChannel, platform: Platforms) {
Comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/connections.service.ts
> + * Contains all the required database flow methods for writing and reading blocks information
Inadequate comment
Focus on the why

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/connections.service.ts
> +  async getConnByOption(optionId: string): Promise<Connection> {
Comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/connections.service.ts
> +  async getConnBySourceId(blockId: string): Promise<Connection> {
Inadequate coment

Add @param blockId - The ID of the block that is searched for the connection

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/connections.service.ts
> +  async getFirstConn(): Promise<Connection> {
getRootConnection?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/cursor.service.ts
> +import { BotDataService } from './data-service-abstract.class';
Order of imports

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/cursor.service.ts
> +export class CursorDataService extends BotDataService<Cursor> {
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/data-service-abstract.class.ts
> +    private repo$: Repository<T>
Add comment. Should this be protected?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/data-service-abstract.class.ts
> +    async getDocumentById(id: string, path: string){
Avoid always having to always pass the path.

Perhaps pass _repo: Repository<T> as a constructor parameter.

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/data-service-abstract.class.ts
> +    async getDocumentById(id: string, path: string){
That requires all inheriting classes to create the repo in their constructor

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/messages.service.ts
> +  private _docPath: string;
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/messages.service.ts
> + * Contains all the required database flow methods for the messages collection
Inadequate comment.

Add what messages are

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/data-services/messages.service.ts
> +    this._docPath = `end-users/${msg.phoneNumber}/platforms/${msg.platform}/messages`
Can be avoided by requiring super to pass the repo as an argument

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +import { SendMessageFactory } from '@app/functions/messages/whatsapp';
Order of imports

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +export class ChatBotMainService {
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +    private _msgDataService$: MessagesDataService,
Too many imports/too high coupling

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/main-chatbot.service.ts
> +  async run(req: RawMessageData) {
To run through together

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/match-input/match-input.service.ts
> + * Contains methods to match options and user input
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/match-input/strategies/exact-match.strategy.ts
> +export class ExactMatch implements MatchStrategy {
{ on new line

No comment?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/question-block.service.ts
> +export class QuestionMessageService extends NextBlockService {
{ on new line

Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/question-block.service.ts
> +    async getNextBlock(msg: BaseMessage, lastBlock?: QuestionMessageBlock): Promise<Block>{
Comment?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/question-block.service.ts
> +        const selectedOptionIndex = matchInput.match(msg.message, lastBlock.options)
Clarify the procedure with comments

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/text-block.service.ts
> +export class TextMessageService extends NextBlockService {
{ new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/block-type/text-block.service.ts
> +export class TextMessageService extends NextBlockService {
NextBlockService is a vague abstract class

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/next-block/next-block.factory.ts
> +            case StoryBlockTypes.TextMessage:
Two spaces only please, not four

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/process-message/process-message.service.ts
> +export class ProcessMessageService {
Comment?

{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/add-message-rest.handler.ts
> +export class AddMessageHandler extends FunctionHandler<RawMessageData, RestResult200> {
Comment?

{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/factories/platform-resolver.factory.ts
> +export class AddMessageFactory {
Comment?

{ new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-message.service.ts
> +export abstract class AddMessageService<T> {
{

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-message.service.ts
> +  /** Inteprets the message as text and saves it to db */
Describe input params and expected output (if any - if none why not?)

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-whatsapp-message.service.ts
> +export class AddWhatsappMessage extends AddMessageService<WhatsappChannel> {
{ new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-whatsapp-message.service.ts
> +export class AddWhatsappMessage extends AddMessageService<WhatsappChannel> {
Indeed, base service then channel specific implementations (y)

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-whatsapp-message.service.ts
> +  async addMessage(msg: RawMessageData, channel: WhatsappChannel) {
Comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-whatsapp-message.service.ts
> +export class AddWhatsappMessage extends AddMessageService<WhatsappChannel> {
But.. Switch should be per block type and not per channel.

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/messages/add-message/src/lib/services/add-whatsapp-message.service.ts
> +  protected async _addImageMessage(msg: WhatsAppResponse, channel: WhatsappChannel): Promise<BaseMessage> {
Cannot all be in one class. Create seperate function-files for this

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/onboarding/src/lib/register-user.handler.ts
> + * Register User Handler. Records all onboarding information of a user
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/onboarding/src/lib/register-user.handler.ts
> +  private async _registerEndUser(req: {phoneNumber: string; orgId: string; storyId: string, platform: Platforms }, tools: HandlerTools): Promise<ChatInfo>{
Doesn't make sense to just move all logic into a private method. Then why not jsut keep it in the main fn?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/conversations/onboarding/src/lib/register-user.handler.ts
> +    const newChat = await chatBotStore.chatInfo().registerChatInfo(chatInfo, req.platform)
Long method chain, add coment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/factories/resolve-platform.factory.ts
> +/** Factory to resolve the platform to send the message to
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/factories/resolve-platform.factory.ts
> +    resolvePlatform(){
Comment?

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/factories/resolve-platform.factory.ts
> +            case Platforms.WhatsApp:
Delay as much as possible the choice of platform. It would be better to switch on the actual sending, not on the full flow

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/handlers/send-message.handler.ts
> + * @Description Used to send message to the desired provider
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/handlers/send-message.handler.ts
> +export class SendMessageHandler extends FunctionHandler< {msg: BaseMessage, block: Block}, void>{
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/handlers/send-message.handler.ts
> +    const client = new SendMessageFactory(data.msg.platform, tools).resolvePlatform()
Comment unclear

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/models/send-message-main.model.ts
> +    protected abstract _sendTextMessage(message: BaseMessage, blockType: StoryBlockTypes, env:any): Promise<any>
No, please use a better abstraction

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/messages/whatsapp/src/lib/models/whatsapp/whatsapp-send-message.model.ts
> +export class SendWhatsAppMessageModel extends SendMessageModel {
Ref above on abstraction

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/handlers/whats-app-message-hook.handler.ts
> +export class WhatsAppMessageHookHandler extends FunctionHandler<{ val: BotProvider }, RestResult> {
No comment

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/handlers/whats-app-message-hook.handler.ts
> +    if (this._dataResIsEmpty(data)) {
Code unreadable. Too close too each other

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/handlers/whats-app-message-hook.handler.ts
> +  private _dataResIsEmpty(data) {
Always use /** */ for classes, methods, ... unless when comment code

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/handlers/whats-app-message-hook.handler.ts
> +      const resp = await axios.post('https://europe-west1-ele-convl-manager-7cd0a.cloudfunctions.net/addMessage', payload, {
Load from .env

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/utils/convert-whatsapp-payload.util.ts
> +export function __ConvertWhatsAppApiPayload(payload: any): WhatsAppResponse {
{ on new line

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/utils/convert-whatsapp-payload.util.ts
> +  const _whatsAppResponse = {
formattedPayLoad.entry[0].changes[0].value is always used. Just load it into a seperate var

2022-10-12 15:41 UTC, jrosseel commented on libs/functions/webhooks/src/lib/utils/convert-whatsapp-payload.util.ts
> +function _FormatWhatsAppPayLoad(payload): RawWhatsAppApiPayload {
Add type of payload

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/blocks/connection/src/lib/connection.model.ts
> +export interface Connection extends IObject {
Comment???

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/blocks/default-block/src/lib/default-block.model.ts
> +export interface DefaultBlock extends IObject{
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/blocks/story-block/src/lib/story-block.model.ts
> +export type StoryBlock = TextMessageBlock | QuestionMessageBlock
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/channel/src/lib/base-channel.interface.ts
> +export interface BaseChannel extends IObject {
Inadequate comment

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/channel/src/lib/base-channel.interface.ts
> +  storyId: string;
Use /** */ for attributes

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/channel/src/lib/whatsapp-channel.interface.ts
> +
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/main/message-data/src/lib/message-data.model.ts
> +export interface MessageData {
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/bot/main/provider/src/lib/provider.model.ts
> +export interface Provider extends IObject {
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/admin/system/src/lib/event.interface.ts
>  export interface Event
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/admin/system/src/lib/platform-types.enum.ts
>  export enum Platforms {
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/admin/system/src/lib/platform-types.enum.ts
>  export enum Platforms {
Use numbers for the enum to save storage

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/chats/src/lib/chat.interface.ts
>  export interface Chat extends IObject
Comment???? 
+ comment on params

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/messages/src/lib/chat-message.interface.ts
> +  export interface Chat extends IObject{
Comment????
Duplicate chat interface?

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts
> +  message       : any;
Any??

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/conversations/messages/src/lib/raw-chat.interface.ts
> +export interface RawMessageData extends IObject{
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/functions/src/lib/base/bot-provider.enum.ts
> +export enum BotProvider{
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/functions/src/lib/whatsapp/raw-whatsapp-payload.interface.ts
> +export interface WhatsAppEntryFormData {
Comment????

2022-10-12 15:41 UTC, jrosseel commented on libs/model/convs-mgr/functions/src/lib/whatsapp/whatsapp-location-message.interface.ts
> +interface LocationInfo{
Also naming. This is very Whatsapp-specific interface so should be whatsapp only.

Differentiate between base types and channel-specifiic types. Use inheritence where possible

2022-10-12 15:41 UTC, jrosseel commented on libs/util/ngfi/functions/src/lib/gc-function.class.ts
> +              private  _environment: Environment)
Use .ENV instead

2022-10-24 09:16 UTC, jrosseel requested changes

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    const pauseMessage: BaseMessage = {
Why is this called pauseMessage? And the method is called sendTextMessage..

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +   * Takes the inteprated message and determines the next block
Comment is not clear to me

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    const processMessage = new ProcessMessageService(this._cursorDataService$, this._connService$, this._blocksService$);
We really need a DI container

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    const processMessage = new ProcessMessageService(this._cursorDataService$, this._connService$, this._blocksService$);
Next task once this is merged!

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    if (!userActivity) {
Shorthand return patterns are better for tail statements (the last statement of a fn)

return !userActivity ? ... : ...

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    if (!userActivity) {
Await is not necessary as you're at the tail and the calling fn will most likely await

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    if (!userActivity) {
The method is already async so it's clear you're returning a rpomise

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +  async sendMessage(data: { msg: BaseMessage; block?: StoryBlock }, endUserPhoneNumber: string) {
Create real type instead of this inline one

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +  async sendMessage(data: { msg: BaseMessage; block?: StoryBlock }, endUserPhoneNumber: string) {
Data is a bad name for a variable. Everything is data, what is this

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-main.service.ts
> +    const client = new SendMessageFactory(data.msg.platform, this._tools).resolvePlatform()
DI container

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> + * Manages the main operations of the bot
What does this mean??

Please put clear comments

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +    this.platform = platform;
Since you're assigning everything in the parameter list (private _msg..., you might as well assign platform in the parameter list as well

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +  async main(rawMessage: RawMessageData) {
Means nothing. What is happening here?

No comment + main is bad naming

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +        const nextBlock = await bot.processMessage(baseMessage);
const reply?

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +        this.promises.push(bot.updateCursor(nextBlock))
Naming 🤦

this.promises??

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +        await bot.sendMessage({ msg: baseMessage, block: nextBlock }, baseMessage.phoneNumber);
bot.reply would be nice

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +        await Promise.all(this.promises);
This needs to be better named and described

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +      case ChatStatus.Paused:
I feel there's duplication in the codebase. I've seen this before

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +  private async _init(req: RawMessageData) {
Move to seperate file. init-chat.function.ts

2022-10-24 09:16 UTC, jrosseel commented on libs/functions/chatbot/src/lib/services/bot-engine-chat-manager.service.ts
> +    const interpretToBaseMessage = new ReceiveInterpreterFactory().resolvePlatform(req.platform).resolveMessageType(req.messageType);
Can be named more easily as unpackMessage or something

2022-11-03 11:58 UTC, ReaganCn commented
All requested changes addressed in PR #124

2022-11-07 13:35 UTC, merged