:sparkles: Configurations for assessment retry and story flow.
italanta/elewa pull request #971
Opened 2024-07-29 11:31 UTC by Beulah-Matt

# Description
Add options for 
- Conditions to retry an assessment.
- Retry is based on default (can retry) or can retry when they fail.
- Learning experience after an assessment is completed, based on completion or completion and passing the assessment.

Fixes [CLM-55]

## Type of change
- [ ] New feature (non-breaking change which adds a feature)

# Screenshot (optional)
<img width="1149" alt="Screenshot 2024-07-29 at 14 24 41" src="https://github.com/user-attachments/assets/ad1bab17-dc25-4063-bed1-8ae3ad90de86">

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2024-07-31 09:49 UTC, ReaganCn requested changes

2024-07-31 09:49 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts
> +      console.log(value);
Remove console.log

2024-07-31 09:49 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts
> +    debugger
pushed debugger

2024-08-01 07:48 UTC, ReaganCn requested changes
I forgot about your value changes. Please refrain from using that in something as simple as a toggle between two states.

2024-08-01 07:48 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts
>        }
Something I had forgot. Please use on click event instead of value changes. onClick is a much simpler and efficient way to solve this problem. Use a variable to store the two states of the control, and then the onClick event to toggle.

2024-08-02 07:18 UTC, Beulah-Matt commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts
>        }
Tell me if the changes I have made work

2024-08-07 07:13 UTC, ReaganCn approved these changes

2024-08-07 07:14 UTC, merged