💄 Clm 454 - Bots - Add teal colour to View All button
italanta/elewa pull request #980
Opened 2024-08-08 06:49 UTC by fraciah

# Description

Addition of background color to view all button

Before:
![c2](https://github.com/user-attachments/assets/82b0e4df-4b54-4a6d-88d2-acad2b208bcd)

After:
![Capture2](https://github.com/user-attachments/assets/ed322b4c-06d8-44d3-b5d7-20e556e5ac56)

2024-08-08 13:07 UTC, ReaganCn requested changes

2024-08-08 13:07 UTC, ReaganCn commented on libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.scss
> +		background-color: teal;
Use scss variables for color. Check the color from `variables.scss`, then use var(--variable-name) here

2024-08-09 07:21 UTC, fraciah commented on libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.scss
> +		background-color: teal;
Done

2024-08-12 09:35 UTC, ReaganCn approved these changes

2024-08-12 09:35 UTC, merged