💄✏️Clm 490 - User Groups - Design changes
italanta/elewa pull request #987
Opened 2024-08-14 12:22 UTC by fraciah

# Description

Set the user groups table background to white.
Add highlight colour to a row on hover.
Fix whatsapp typo.

# Screenshots
Before:
![c1](https://github.com/user-attachments/assets/fff230d2-885e-40a7-ab66-bc23cd2d9097)

After:
![c2](https://github.com/user-attachments/assets/ef67a084-d0dd-4ac0-8400-b8ee1ba6d419)

On hover:
![onHover](https://github.com/user-attachments/assets/e98442a9-9d91-4d0b-8485-ad87b93a1897)

2024-08-15 12:29 UTC, jrosseel requested changes

2024-08-15 13:54 UTC, fraciah commented on libs/features/convs-mgr/user-groups/src/lib/components/user-groups-list/user-groups-list.component.scss
> +    background-color: rgba(31, 122, 140, 0.1);
Will create one for it

2024-08-21 06:44 UTC, ReaganCn commented on libs/features/convs-mgr/user-groups/src/pipes/platform-pipe.pipe.ts
> +export class PlatformPipe implements PipeTransform {
A pipe made to just capitalize the first letter of the platform, might be an overkill, something the title case pipe should be able to do. Instead of this, check why the titlecase pipe is not working or create a pipe to capitalize any first letter of a string or just use css:
```
.your-classname:first-letter {text-transform: uppercase}
```

2024-08-21 06:46 UTC, ReaganCn requested changes
Check my comments

2024-08-21 09:29 UTC, fraciah commented on libs/features/convs-mgr/user-groups/src/pipes/platform-pipe.pipe.ts
> +export class PlatformPipe implements PipeTransform {
The title case pipe works for all platforms except whatsapp. The platform name "whatsapp" should be"WhatsApp". That would require a custom pipe.

2024-08-21 09:37 UTC, ReaganCn reviewed
> The title case pipe works for all platforms except whatsapp. The platform name "whatsapp" should be"WhatsApp". That would require a custom pipe. 

libs/elements/layout/convs-mgr

2024-08-21 13:27 UTC, fraciah commented
The custom pipe defined under libs/elements/custom-pipes was first created in clm-499. That branch is merged with this one but now with its import for the pipe module.

2024-08-22 07:33 UTC, ReaganCn approved these changes

2024-08-22 07:33 UTC, merged