💄✏️ Clm 499 - Settings - Company Info
italanta/elewa pull request #988
Opened 2024-08-14 12:44 UTC by fraciah

# Description

Fix channel's platform typo and logo appearance.

# Screenshots 
![b4](https://github.com/user-attachments/assets/2eb4b9e4-6da4-4fde-9df3-341ac4fdc12b)
![after](https://github.com/user-attachments/assets/299b9b93-865c-4f0b-9fee-d96bc0002c05)

![Capture](https://github.com/user-attachments/assets/6f101984-a01e-4c2b-85bc-24ea6813dfb0)
![Capture2](https://github.com/user-attachments/assets/7c596f9a-8c15-4813-bcce-3ee9bd1e322c)

2024-08-15 12:30 UTC, jrosseel requested changes

2024-08-15 12:30 UTC, jrosseel commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.html
> +          <td mat-cell *matCellDef="let element"> {{transformChannelPlatform(element.type)}} </td>
Please use a local pipe

2024-08-15 12:30 UTC, jrosseel commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.html
> +          <td mat-cell *matCellDef="let element"> {{transformChannelPlatform(element.type)}} </td>
https://v17.angular.io/guide/pipes-overview

2024-08-15 12:30 UTC, jrosseel commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.html
> +          <td mat-cell *matCellDef="let element"> {{transformChannelPlatform(element.type)}} </td>
Local means declared in the local module/package

2024-08-21 06:58 UTC, ReaganCn requested changes

2024-08-21 06:58 UTC, ReaganCn commented on libs/private/features/convs-mgr/settings/organisation-details/src/lib/pipes/platform.pipe.ts
> +import { Pipe, PipeTransform } from '@angular/core';
Check my comments in CLM - 490

2024-08-22 07:33 UTC, merged