:lipstick: {refactor} Side nav layout #24
italanta/elewa pull request #99
Opened 2022-10-13 10:00 UTC by faisoabdirisak

# Description

I have edited and designed the side nav according to the design needed.

Reference [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) -

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

![Screenshot (504)](https://user-images.githubusercontent.com/91128983/195567080-9e19af47-a152-4ec0-8150-ce80801c634f.png)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-13 14:14 UTC, ReaganCn requested changes
Good approach. See additional comments below

2022-10-13 14:14 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +              <i class="fas fa-bars"></i>
Use fort awesome icons for consistency across the codebase

2022-10-13 14:14 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +                  <i class='fas fa-tachometer-alt'></i>
Same here. Use fort awesome

2022-10-13 14:14 UTC, ReaganCn commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.html
> +    <i class="fa fa-search"></i>
Same here. Use fort awesome

2022-10-13 14:16 UTC, ReaganCn commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +                <span class="main-text">Main</span>
Use multi-lang

2022-10-14 09:45 UTC, faisoabdirisak commented
made  the changes

2022-10-17 07:54 UTC, ReaganCn approved these changes
Good work! Keep it up

2022-10-17 08:05 UTC, merged