🐛 CLM 488 - Users - platform filter not working
italanta/elewa pull request #993
Opened 2024-08-20 12:04 UTC by fraciah

# Description

Fix users platform filter dropdown

2024-08-21 07:14 UTC, ReaganCn requested changes

2024-08-21 07:14 UTC, ReaganCn commented on libs/features/convs-mgr/learners/src/lib/utils/learner-filter.util.ts
> +import { toLower } from "lodash";
There is an inbuild javascript string function to convert to lowercase. Use that instead

2024-08-21 08:13 UTC, fraciah commented on libs/features/convs-mgr/learners/src/lib/utils/learner-filter.util.ts
> +import { toLower } from "lodash";
That's an unused import. I'll remove it.

2024-08-22 07:36 UTC, ReaganCn approved these changes

2024-08-22 07:37 UTC, merged