✨  [CLM-34] Question Banks
italanta/elewa pull request #997
Opened 2024-08-22 10:03 UTC by Beulah-Matt

# Description
- Add Questions to a bank
- Edit the question
- Delete the question
- Select the question and choose to add it to an assessment
- Allow adding multiple questions to multiple assessments

Fixes # [CLM-34] Question Banks

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

[CLM-34]: https://elewake.atlassian.net/browse/CLM-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-22 12:53 UTC, ReaganCn requested changes
Good attempt. Just some code cleanup required.

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/add-question-to-assessment/add-question-to-assessment.component.ts
> +          console.error('Error adding questions to assessments', err);
Redundant to the snackbar message

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts
> +      panelClass: "__addModal"
the class can be applied directly to the modal component. Instead of this. So that the styling is limited to HTML & SCSS only

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-media-upload/question-bank-media-upload.component.ts
> +export class QuestionBankMediaUploadComponent implements OnInit
The same component already exists on the assessment create side. Reuse that, unless the design is different

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-question-form/question-bank-question-form.component.scss
> +		border: solid #B8AFDA 2px;
Use scss variables for colors

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-card/question-card.component.scss
> +.question-feedback{
scss variables for all the colors in this file too

2024-08-22 12:53 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-card/question-card.component.ts
> +        width: "600px"
Only do styling on the component level. HTML/CSS files

2024-08-22 12:53 UTC, ReaganCn commented on libs/state/convs-mgr/conversations/assessments/src/lib/stores/assessment-question.store.ts
> +      tap({
Remove the redundant tap + console.log. The result of this function should be returned and shown to the user

2024-08-22 13:36 UTC, Beulah-Matt commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-media-upload/question-bank-media-upload.component.ts
> +export class QuestionBankMediaUploadComponent implements OnInit
The component expects an assessment form, which we do not need for this.

2024-09-02 10:07 UTC, ReaganCn requested changes

2024-09-02 10:07 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-media-upload/question-bank-media-upload.component.ts
> +export class QuestionBankMediaUploadComponent implements OnInit
Just make it reusable. Exract the logic to a different component and import it in both the question bank and the assessment question

2024-09-04 07:23 UTC, ReaganCn commented on libs/elements/layout/modals/src/lib/media-upload-modal/media-upload.component.ts
> +    if(this.formViewMode === 1){
Always use the enum for comparison

2024-09-04 07:29 UTC, ReaganCn commented on libs/elements/layout/modals/src/lib/media-upload-modal/media-upload.component.ts
> +import { FileStorageService } from '@app/state/file';
Circular dependency. You will have to move this file to the assessment lib because it has too many dependencies to be placed in elements/layout without a circular issue.

2024-09-04 07:34 UTC, ReaganCn commented on libs/elements/layout/modals/src/lib/media-upload-modal/media-upload.component.ts
> +    if (this.questionFormGroup) {
Its safer to use an enum for this. this.data.questionSectionType === QuestionSectionType.QuestionBank.
Using the formgroup might work but will cause bugs if someone moves from question banks to assessments or vice versa. So the form won't be null

2024-09-04 07:35 UTC, ReaganCn commented on libs/elements/layout/modals/src/lib/media-upload-modal/media-upload.component.ts
> +    if (this.questionFormGroup) {
This approach will also make the code cleaner as you wouldn't need an additional else if

2024-09-04 07:41 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts
> +        this.isImage = type === 'image';
instead of isImage, you should have a variable called 'mediaType' or something similar. Because using image as the base condition will get more confusing when we add other media types.

2024-09-04 07:43 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts
> +    if(questionToAdd.id !== ''){
'' in javascript is interpreted as falsy so `if(questionToAdd.id)` will still work. 
https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2024-09-04 07:44 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts
> +    if (this.searchTerm.trim() === '') {
https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2024-09-06 11:18 UTC, ReaganCn requested changes

2024-09-06 11:18 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts
> +    }else{
Duplicate statements in both if conditions. Always skim through your code to catch these obvious issues.

2024-09-06 11:18 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/modals/media-upload-modal/media-upload.component.ts
> +        if (this.questionFormGroup) {
You can also use the formView mode for this if statement

2024-09-06 11:18 UTC, ReaganCn commented on libs/state/convs-mgr/conversations/assessments/src/lib/stores/assessment-question.store.ts
> +            this._org$$.get().pipe(
Use a combination of switchMaps to get the org and create the question. Using subscribe here is never allowed because will cause perfomance chaos

2024-09-11 09:07 UTC, ReaganCn requested changes

2024-09-11 09:07 UTC, ReaganCn commented on libs/features/convs-mgr/conversations/assessments/src/lib/modals/media-upload-modal/media-upload.component.ts
> +    this.fileAccept = data.fileType === 'image' ? 'image/*' : 'video/*';
I had requested changes on this condition.

2024-09-19 08:12 UTC, ReaganCn approved these changes

2024-09-19 08:12 UTC, merged